### ISSUE TITLE
종목명이 영어로 반환됨

### ISSUE THREAD

**Issue by dykim114** [sharebook-kr/pykrx#101]
안녕하세요.

그동안 잘 사용하고 있었는데 
오늘 아래 함수를 호출하면 종목명이 한글이 아닌영문으로 반환됩니다.
stock.get_market_ticker_name(ticker)

확인부탁드립니다.

감사합니다.

**Comment by mr-yoo** [comment]
안녕하세요. 최근 krx웹서버의 변경이 있어  종목명이 영어로 반환되는 것을 확인했습니다. https://github.com/sharebook-kr/pykrx/issues/100 에서 문제를 수정했으니 모듈 업데이트 후 사용해 주세요

pip install -U  pykrx

**Comment by dykim114** [comment]
네 방금 새로 설치해서 사용하니 잘됩니다. 감사합니다.
