### ISSUE TITLE
어제까지 됐던게 오늘은 안되네요.

### ISSUE THREAD

**Issue by kjr5344** [sharebook-kr/pykrx#103]
안녕하세요 .
덕분에 잘 사용하고 있습니다. 감사합니다.
그런데 오늘은 안되네요.
API를 이것저것 해봐도 전부 json decode 에러가 발생해서 혹시 서버점검인가 싶기도 하구요.
아래 다른 이슈로 인해 update해보라 그래서 update해봤는데 동일합니다.
감사합니다.

  File "/Users/kang/opt/anaconda3/envs/stock/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mr-yoo** [comment]
현재 krx 웹페이지가 서버점검중입니다.
http://www.krx.co.kr/
