### ISSUE TITLE
get_market_net_purchases_of_equities 오류 문의드립니다. 

### ISSUE THREAD

**Issue by redbluesepia** [sharebook-kr/pykrx#104]
코드 예제에 적혀있는대로
df = stock.get_market_net_purchases_of_equities("20210115", "20210122", "KOSPI", "개인")을 실행하면

" AttributeError: module 'pykrx.stock' has no attribute 'get_market_net_purchases_of_equities' "  라고 뜨네요. 

현재 이 함수는 지원이 안되는건지 문의드립니다.

**Comment by redbluesepia** [comment]
제가 저자님 파이썬 코드를 보니깐 실제 함수는
"get_market_net_purchases_of_equities_by_ticker"를 써야 하네요.  이렇게 귀중한 코드를 공유해주셔서 감사드립니다. 꾸벅..

**Comment by mr-yoo** [comment]
최근에 쓰기 어려워서 API이름을 짧게 줄이고 있었는데 오타가 포함돼 있었나봅니다. 
https://github.com/sharebook-kr/pykrx/commit/e434c1c3d56267f36f3d737b54a1124faacaeb38 커밋에서 오타를 수정했습니다.

몇일 내로 PIP 업데이트하면 다음과 같이 사용하실 수 있을 겁니다. 
```python
df = stock.get_market_net_purchases_of_equities("20210115", "20210122", "KOSPI", "개인")
df.head()
```
```text
            종목명     매도거래량      매수거래량    순매수거래량         매도거래대금         매수거래대금        순매수거래대금
티커
005930     삼성전자  79567418  102852747  23285329  6918846810800  8972911580500  2054064769700
000270      기아차  44440252   49880626   5440374  3861283906400  4377698855000   516414948600
005935    삼성전자우  15849762   20011325   4161563  1207133611400  1528694164400   321560553000
051910     LG화학    709872     921975    212103   700823533000   908593419000   207769886000
096770  SK이노베이션   4848359    5515777    667418  1298854139000  1478890602000   180036463000
```
