### ISSUE TITLE
pykrx 상업용도 사용 시 라이센스는 어떻게 되나요?

### ISSUE THREAD

**Issue by wkd8176** [sharebook-kr/pykrx#107]
pykrx를 사용한 페이지에 애드센스등의 광고 혹은 상업 사용 시 라이센스가 어떻게 되는가요?
krx 쪽에서는 데이터 접근 시 데이터 라이센스 비용 지불이 필요한 것 같은데 그것과는 별개인가요?
라이센스 관련해서는 지식이 부족하여 문의 드립니다.

**Comment by mr-yoo** [comment]
pykrx 모듈은 [한국거래소(KRX)](http://www.krx.co.kr/main/main.jsp) 데이터를 스크래핑합니다. 한국거래소가 API를 공식적으로 지원하지 않기 때문에 pykrx에서 스크래핑한 데이터를 가공해서 보여줍니다. 

스크래핑 행위 자체가 불법은 아니지만, 웹 서버에 부하를 일으켜 다른 사용자의 원활한 서비스를 방해하면 문제가될 수 있습니다. 더욱이 수집한 데이터를 상업적으로 사용할 경우 문제가 될 수 있습니다. 법과 관련된 내용이라서 이 부분은 변호사 상담이 필요할 것 같습니다.  한국 거래소에 스크래핑한 데이터를 사용해도 되는지 문의해 보는 것도 하나의 방법이겠네요.
