### ISSUE TITLE
교육용으로 사용해도 될까요?

### ISSUE THREAD

**Issue by woniesong92** [sharebook-kr/pykrx#108]
안녕하세요, 문서화 잘 된 좋은 API 코드를 공유해주셔서 감사합니다.
혹시 pykrx 를 교육용으로 사용해도 될까요?

**Comment by mr-yoo** [comment]
`pykrx`는 오픈 소스이니 마음껏 사용하세요. KRX에서 스크래핑 하기 때문에 도의적인 수준으로 데이터를 가져다 쓰시구요.

**Comment by woniesong92** [comment]
감사합니다!
