### ISSUE TITLE
JSONDecodeError:Expection value 에러메시지.. 

### ISSUE THREAD

**Issue by jswoo** [sharebook-kr/pykrx#11]

**Comment by mr-yoo** [comment]
버전 및 모듈 version 문제인 것으로 추정되는데 다음 내용 확인 부탁드립니다.
1) 모듈 버전 확인
설치된 pykrx 버전 확인 부탁드려요.
```pip install -U pykrx```

2) 설치된 모듈 정보
다음 명령으로 설치된 모듈 리스트를 전달 부탁드려요.
```pip list```
