### ISSUE TITLE
기본데이터 조회 df = stock.get_market_fundamental("20220321")

### ISSUE THREAD

**Issue by d10000usd** [sharebook-kr/pykrx#111]
BPS           PER         PBR     EPS        DIV    DPS
티커                                                                 
095570     6089      0.000000    0.950195       0   3.619141    210
006840    50471      0.000000    0.429932       0   1.830078    400
027410    15781     18.453125    0.330078     285   2.089844    110
282330    40317     25.062500    4.421875    7103   1.349609   2400
138930    26781      5.148438    0.290039    1498   4.148438    320
001460   538911     20.046875    0.810059   21904   0.250000   1100
001465        0      0.000000    0.000000       0   0.649902   1150
001040   130202     31.421875    0.620117    2581   2.470703   2000
079160     3812      0.000000    7.078125       0   0.000000      0
00104K        0      0.000000    0.000000       0   2.810547   2000
000120   146331     23.046875    0.899902    5683   0.000000      0
011150     1823     69.000000    2.189453      58   0.000000      0
011155        0      0.000000    0.000000       0   0.000000      0
.....
.....
.....
.....
데이터 조회하면 per eps div  값이 '0'
나오는건 뭔가요???

버전은 최신이고 이슈사항 읽어 봤는데요... 
대략 다 뽑아서 정렬해보면 음수는 0으로 나오는거 같거든요. 
다른 소수점 자리도 안맞는거 같아서요...

-----
http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020301
krx 사이트 데이터에 문제가 있네요..
결론은 소스문제는 아니듯.

**Comment by mr-yoo** [comment]
수익이 없어서 EPS 값이 `-`로 서버에서 전송되고 이를 모듈내에서 0으로 바꿔서 출력하고 있습니다. 
KRX 사이트에서는 음수로 표시되는데 모듈에서 다르게 처리하고 있다면 알려주세요.
