### ISSUE TITLE
이 라이브러리는 크롬 프로세스 같은 웹 드라이버를 사용해서 스크래핑을 하는건가요?

### ISSUE THREAD

**Issue by mmol93** [sharebook-kr/pykrx#112]
설명을 보면 스크래핑을 한다고 적혀있는데

selenimum 같은 라이브러리를 사용해서 스크래핑을 하는건지 궁금합니다!

**Comment by mmol93** [comment]
설명을 보면 스크래핑을 한다고 적혀있는데

selenimum 같은 라이브러리를 사용해서 스크래핑을 하는건지 궁금합니다!

**Comment by mr-yoo** [comment]
`selenium`은 느려서 `requests`와 `BeautifulSoup`을 사용해서 스크래핑합니다.

**Comment by mmol93** [comment]
감사합니다!
