### ISSUE TITLE
ETF의 거래실적 정보 스크래핑

### ISSUE THREAD

**Issue by bkpark99** [sharebook-kr/pykrx#113]
ETF 종목에 대해 get_market_trading_value_by_date()를 사용했더니 오류가 나네요. ETF 종목에 대한 trading 정보를 얻고 싶은데요, 어떻게 하면 될까요 ?

**Comment by mr-yoo** [comment]
사용하신 코드를 올려주실 수 있을까요?

**Comment by bkpark99** [comment]
다음 함수는 종목 코드를 매개변수를 받아서 가격 정보와 거래 정보 DataFrame을 반환합니다.
일반 종목은 잘 동작하는데, ETF 종목 코드를 받을 경우 stock.get_market_trading_value_by_date()가 정상적인 데이터를 반환하지 않습니다. 

def read_price(code, append):
        # FinanceDataReader와 pykrx를 이용하여 가격정보와 거래정보를 읽어 DataFrame을 반환
        # append
        frdate = '19980124'
        todate = effdate()
        if append == 1:
            with self.conn.cursor() as curs:
                sql = f"SELECT max(date) FROM daily_price WHERE code='{code}'"
                curs.execute(sql)
                rs = curs.fetchone()  
                if rs[0] :
                    frdate = rs[0].strftime('%Y%m%d')
      
        df = fdr.DataReader(code, frdate, todate)
        df.columns=['open', 'high', 'low', 'close', 'volume', 'diff']
       
        vol = stock.get_market_trading_value_by_date(frdate, todate, code)    // code가 일반종목은 문제없는데, ETF일 경우 오류발생
        vol.columns = ['ivolume', 'evolume', 'pvolume', 'fvolume', 'sum']
        df[['ivolume', 'evolume', 'pvolume', 'fvolume', 'sum']] = vol[['ivolume', 'evolume', 'pvolume', 'fvolume', 'sum']]

        return df

**Comment by bkpark99** [comment]
아래 함수는 종목 code를 매개변수로 받아서 가격정보와 거래정보를 담은 DataFrame을 반환합니다.
일반 종목은 정상동작하지만, ETF 종목 code를 받을 경우 거래 정보가 반환되지 않네요.

def read_price(code, append):
        # FinanceDataReader와 pykrx를 이용하여 가격정보와 거래정보를 읽어 DataFrame을 반환
        # pages_to
        frdate = '19980124'
        todate = effdate()
        if append == 1:
            with self.conn.cursor() as curs:
                sql = f"SELECT max(date) FROM daily_price WHERE code='{code}'"
                curs.execute(sql)
                rs = curs.fetchone()  
                if rs[0] :
                    frdate = rs[0].strftime('%Y%m%d')
      
        df = fdr.DataReader(code, frdate, todate)
        df.columns=['open', 'high', 'low', 'close', 'volume', 'diff']
        df['date'] = df.index       # index를 열로 추가
        vol = stock.get_market_trading_value_by_date(frdate, todate, code)
        vol.columns = ['ivolume', 'evolume', 'pvolume', 'fvolume', 'sum']
        df[['ivolume', 'evolume', 'pvolume', 'fvolume', 'sum']] = vol[['ivolume', 'evolume', 'pvolume', 'fvolume', 'sum']]

        return df

**Comment by bkpark99** [comment]
답변 감사합니다. 저도 짬짬히 해보도록 하겠습니다.

**Comment by mr-yoo** [comment]
c35a6f7724235088156f660c48e569c12b9d5ac8 에 해당 내역 추가했습니다. 
`pip`은 1주일 내로 업데이트될 예정입니다.


----

`get_etf_trading_volumne_and_value` 함수는 거래량과 거래대금 정보를 조회합니다. 시작일자와 종료일자를 입력하면 투자자별 거래 실적이 조회됩니다.
```python
df = stock.get_etf_trading_volumne_and_value("20220415", "20220422")
print(df.head())
```
```
              거래량                              거래대금
                매도        매수    순매수            매도            매수         순매수
금융투자    375220036   328066683 -47153353   3559580094684   3040951626908 -518628467776
보험         15784738    15490448   -294290    309980189819    293227931019  -16752258800
투신         14415013    15265023    850010    287167721259    253185404050  -33982317209
사모          6795002     7546735    751733     58320840040    120956023820   62635183780
```

`query_type1`과 `query_type2`를 입력하면 일자별로 세부 내역을 조회합니다.
- `query_type1`은 `거래대금`과 `거래량` 중 하나를 입력합니다.
- `query_type2`는 `순매수`, `매수`, `매도` 중 하나를 입력합니다.


```python
df = get_etf_trading_volumne_and_value("20220415", "20220422", query_type1="거래대금", query_type2="순매수")
print(df.head())
```
```
                    기관    기타법인         개인        외국인 전체
날짜
2022-04-15   25346770535  -138921500  17104310255  -42312159290    0
2022-04-18 -168362290065  -871791310  88115812520   81118268855    0
2022-04-19  -36298873785  7555666910  -1968998025   30712204900    0
2022-04-20 -235935697655  8965445880  19247888605  207722363170    0
2022-04-21  -33385835805  2835764290  35920390975   -5370319460    0
```
