### ISSUE TITLE
장중 api 요청시 지연 여부

### ISSUE THREAD

**Issue by Jigunho** [sharebook-kr/pykrx#116]
안녕하세요.
장중에 get_market_ohlcv_by_ticker 함수로 전체 종목의 시세를 읽어오고 있는데요, 해당 함수를 확인해보니 krx 클래스를 사용하는것으로 보이는데 지연이 꽤 발생하는것 같습니다.

(1) 혹시 지연이 대략적으로 어느정도 되는지와
(2) 혹시 네이버 api를 사용한 전체종목 조회 함수의 유무
질문드립니다. 좋은 라이브러리 만들어주셔서 감사합니다.

**Comment by mr-yoo** [comment]
본 모듈은 [한국 거래소](http://data.krx.co.kr/contents/MDC/MAIN/main/index.cmd) 웹페이지에서 데이터를 가져옵니다. 웹페이지의 상태에 따라 가져오는 속도가 다릅니다. 

네이버에서는 OHLCV 하나만 스크래핑하고 있습니다.

**Comment by edgelines** [comment]
한국 거래소 데이터는 약 20분 정도 지연된 데이터 입니다
