### ISSUE TITLE
get_market_fundamental() 조회시 에러

### ISSUE THREAD

**Issue by zeniper** [sharebook-kr/pykrx#117]
df = stock.get_market_fundamental("20220321")

조회시 KeyError가 발생합니다.

KeyError: "None of [Index(['BPS', 'PER', 'PBR', 'EPS', 'DIV', 'DPS'], dtype='object')] are in the [columns]"

버전은 1.0.32로 방금전 업데이트 하고 진행하였습니다.

**Comment by mr-yoo** [comment]
한국거래소에서 데이터를 스크래핑 합니다. 해당 서버 점검으로 간혹 서버의 이용이 불가능할 때가 있습니다. 다시 확인해 보시겠어요? 지금도 안될까요?

**Comment by WOOJOONSIK** [comment]
df = stock.get_market_fundamental("20220321")
df.head(3)

정상 동작되는 모듈입니다.^^

**Comment by YoonHanho** [comment]
방금 코드 실행하니 아래 오류가 발생하네요. 
일시적인 문제일까요? ㅠ.ㅜ 
df = stock.get_market_fundamental("20251208")
> KeyError: "None of [Index(['BPS', 'PER', 'PBR', 'EPS', 'DIV', 'DPS'], dtype='object')] are in the [columns]"
