### ISSUE TITLE
외국인 보유 주식 한도와 관한 질문.

### ISSUE THREAD

**Issue by woonkij** [sharebook-kr/pykrx#12]
안녕하세요, 사용하신 code architecture를 이용해 외국인 보유 주식 한도 (https://marketdata.krx.co.kr/mdi#document=13020402) 를 스크레이핑 하려고 해 보았습니다

` class MKD81006(KrxFileIo):
  @property
    def bld(self):
        return "MKD/13/1302/13020402/mkd13020402"

    def fetch(self, date, mkt, limitType):
        result = self.post(schdate=date, market_gubun=mkt, lmt_tp=limitType)
        return result`

df = MKD81006().fetch("20200630", "ALL", "1") 으로 해 보았습니다.
좋은 라이브러리를 제공해 주셔서 감사합니다!

**Comment by mr-yoo** [comment]
파일로 한 번에 값을 읽어 오므로 다음과 같이 `read_excel()` 메서드로 dataframe으로 변환하면 됩니다. 
```
def fetch(self, date, mkt, limitType):
    result = self.post(schdate=date, market_gubun=mkt, lmt_tp=limitType)
    return pd.read_excel(result)
```

**Comment by mr-yoo** [comment]
이번 기회에 API를 추가했습니다. 
https://github.com/sharebook-kr/pykrx/commit/d60791a75d913973502a0420babee0ff656db29c
