### ISSUE TITLE
공휴일 수집에 대한 질문

### ISSUE THREAD

**Issue by includesorrow** [sharebook-kr/pykrx#121]
(일별 주식 차트)
http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020101

해당 데이터를 수집하려고 pykrx를 사용했습니다.

한국거래소 : [http://data.krx.co.kr/](http://data.krx.co.kr/contents/MDC/MAIN/main/index.cmd)

통계 → 주식 → 종목시세 → 전종목 시세

그런데 2015-01-01 / 2011-01-01 데이터가 수집이 되고 있는데, 혹시 해당 이슈에 대해서 확인해주시면 감사합니다.

**Comment by mr-yoo** [comment]
현재 `get_market_fundamental` 등의 메서드는 공휴일일 경우 가까운 영업일의 데이터를 조회합니다. 비어있는 결과를 반환하는게 좋을 것 같은데요? 의견 있다면 말씀주세요.

**Comment by includesorrow** [comment]
저도 비어있는 결과를 반환하는게 좋을 것 같다는 생각입니다.

**Comment by mr-yoo** [comment]
휴일일 경우 0으로 채워진 DataFrame 반환하도록 수정했습니다.
- get_shorting_volume_by_ticker
- get_shorting_value_by_ticker
- get_index_fundamental_by_ticker
- get_index_ohlcv_by_ticker
- get_market_cap_by_ticker
- get_market_ohlcv_by_ticker
- get_market_price_change_by_ticker
- get_market_fundamental_by_ticker

pip은 몇일 이내에 업데이트될 예정입니다.
