### ISSUE TITLE
일자별 주식종목의 시장구분과 업종명 추가 요청

### ISSUE THREAD

**Issue by youngjae-jeon** [sharebook-kr/pykrx#126]
안녕하세요.

제목과 같이 krx에서 일자별로 전체 주식종목의 시장구분과 업종명을 받을 수 있는 기능을 추가해 주시면 좋겠습니다.

파이스탁 카페에 아래와 같이 동일한 요청 및 질문을 했었습니다.

https://cafe.naver.com/pystock/8855

**Comment by mr-yoo** [comment]
코드는 추가해 놨습니다.
- https://github.com/sharebook-kr/pykrx/commit/7b56a0eb703166750f4d103812bd3c5352cef3cc

PIP은 몇 주 이내라 업데이트 예정입니다.
