### ISSUE TITLE
천 단위 콤마, 소수점 아래 처리 관련

### ISSUE THREAD

**Issue by WonSeokChoi-Unicorn** [sharebook-kr/pykrx#127]
최근 알게 되어서 잘 사용하고 있고, 조회한 내용을 이메일로 발송하는 간이 RPA로 구현 중입니다.

예를 들어

투자자별 거래실적 추이 (거래대금) 조회

의 개인 구분이

600349635 원으로 조회됩니다.

이러면 알아보기 쉽지 않은 것 같아서,

pd.set_option('display.float_format', '{:,}'.format)

같은 옵션을 적용하여 600,349,635 원으로 조회할 수 있을 지 문의합니다.

**Comment by mr-yoo** [comment]
조회한 값을 포맷팅해서 출력하면 될것 같습니다.

```python
value = 600349635
print( f"{value:,} )
```

**Comment by WonSeokChoi-Unicorn** [comment]
> 하나의 값이라면 포맷팅해서 출력하면 됩니다.
> 
> ```python
> value = 600349635
> print( f"{value:,} )
> ```
> 
> 전체 `DataFrame`을 포맷팅한다면 다음과 같이 일괄 적용할 수 도 있습니다.
> 
> ```python
> from pykrx import stock
> import pandas as pd
> 
> pd.options.display.float_format = '{:,}'.format
> df = stock.get_market_ohlcv("20220901", "20220915", "005930")
> df.applymap('{:,.0f}'.format)
> df.head()
> ```

친절하게 알려주셔서 감사합니다.
