### ISSUE TITLE
KRX 종목별 주가 수정주가 옵션 추가

### ISSUE THREAD

**Issue by keepcosmos** [sharebook-kr/pykrx#129]
현재 수정주가는 naver 주식으로 대체하여 요청을 보내는 걸로 알고 있습니다만, 
krx 요청에도 `adjStkPrc` 파라미터를 통해 수정주가를 불러올 수 있습니다.

`adjStkPrc=1` 은 디폴트
`adjStkPrc=2` 은 수정주가

`get_market_ohlcv` 요청 시, adjusted에 따라 naver 로 호출하는 것에 특별한 이유가 있을까요?
그런게 아니라면 krx 로 요청을 통일하는 로직으로 PR을 날려보려 합니다. (혹은 직접 수정하셔도 됩니다.)

**Comment by mr-yoo** [comment]
과거에는 수정주가를 제공하지 않아서 네이버에서 조회했는데요. 
가능 하다면 KRX 하나로 통일하는게 좋을 것 같습니다.  
코드를 수정해 주시면 더욱 좋구요.

**Comment by keepcosmos** [comment]
감사합니다. 혹시 패키지 릴리즈는 언제쯤 예상하시나요?

**Comment by mr-yoo** [comment]
`1.0.39`로 업데이트 했습니다.
https://pypi.org/project/pykrx/#history
