### ISSUE TITLE
get_etf_ohlcv_by_date 지연 문의

### ISSUE THREAD

**Issue by pjw0215** [sharebook-kr/pykrx#131]
안녕하세요.
프로그램은 잘 사용하고 있습니다. 진심으로 감사드립니다.

이전에 사용하던 버전(1.0.32)의 get_market_ohlcv 메소드는
주식, ETF의 가격 정보를 모두 지연없이 불러올 수 있었습니다.

그런데, 최근 업데이트 된 버전(1.0.39)을 설치하고 보니
ETF의 가격 정보를 불러오는 방식이 get_etf_ohlcv_by_date로 분리되었고
이 메소드의 경우 20분의 딜레이가 발생하는 것을 발견했습니다.

혹시 이전처럼 지연없이 ETF 가격 정보를 불러올 수 있는 방법이 있는지 궁금합니다. 감사합니다.

**Comment by mr-yoo** [comment]
KRX 웹서버에서 20분 지연을 둔채로 데이터를 줘서 그렇습니다. 이전에는 우연찮게(?) 바로 데이터를 줬던거 아닌가 생각합니다.  pykrx 모듈에서는 특별한 변경사항이 없습니다.
