### ISSUE TITLE
ETF 개별종목의 일자별 데이터 오류

### ISSUE THREAD

**Issue by Cheongha-Kim** [sharebook-kr/pykrx#132]
안녕하세요. 너무나도 잘 사용하고 있는 개인 유저입니다. 제가 생각했을 때 1가지 문제점이 있어 말씀드립니다.

ETF 거래대금을 불러오고 싶습니다.

1. df =stock.get_etf_trading_volume_and_value("20220908", "20220916", "580011", "거래대금", "순매수")
print(df.head())
 - ETN을 거래대금을 불러오는 코드로 ETF를 불러오지는 못하는 것 같습니다. "580011"도 ETF가 아니라 ETN의 종목코드입니다.

감사합니다.

**Comment by oilandwater** [comment]
ETF 거래실적 관련 함수들에서도 동일한 현상이 발생되는 것으로 보입니다(ETN종목코드로만 조회가능합니다)
확인 부탁드립니다. 감사합니다.

**Comment by mr-yoo** [comment]
우선 `stock.get_etf_trading_volume_and_value` 함수는 `ETF` 종목의 정보를 조회합니다. `580011`은 `580011/KB FnGuide 언택트 ETN` 입니다. 따라서 위 함수로는 결과가 나오지 않는게 맞습니다.

@Cheongha-Kim 님, 제가 이해한게 맞을까요?



`580011/KB FnGuide 언택트 ETN`

**Comment by mr-yoo** [comment]
@oilandwater 님
아직 etn 관련 함수를 구현하지 않았습니다.ㅠ

**Comment by silver0700** [comment]
> 우선 `stock.get_etf_trading_volume_and_value` 함수는 `ETF` 종목의 정보를 조회합니다. `580011`은 `580011/KB FnGuide 언택트 ETN` 입니다. 따라서 위 함수로는 결과가 나오지 않는게 맞습니다.
> 
> @Cheongha-Kim 님, 제가 이해한게 맞을까요?
> 
> `580011/KB FnGuide 언택트 ETN`

네. 함수명대로 ETF를 조회하여야하는데 ETF는 안되고 ETN이 조회가 되고있어요~

**Comment by coolmintmild** [comment]
동일한 내용입니다.

[KODEX 200] 이나 KODEX [KODEX 200선물인버스]과 같은 지수추종 ETF의 거래실적을 불러올 때 문제가 생기네요. 저는 특정 지수추종 ETF관련 된건 줄 알았는데 ETF 전반으로 안되나 보네요.

이런 ETF의 투자자별 거래실적을 불러오고자 하면 

모든 데이터가 0으로 나타나거나 (기간합산: stock.get_etf_trading_volume_and_value('20230101', '20230425', '069500') )

이런 에러메시지가 나타납니다. 
(일자별: stock.get_etf_trading_volume_and_value('20230101', '20230425', '069500', "거래대금", "순매수"))

예시의 KB FnGuide 언택트 ETN(580011)는 잘됩니다. -> 이건 ETF가 아니라 ETN이었네요.

**Comment by mr-yoo** [comment]
`e686bae7`에서 다음 형태로 사용할 수 있도록 수정했습니다.

----

KRX 웹페이지의 `[13106] 투자자별 거래실적` 메뉴에서 `기간 합계` 데이터를 스크래핑합니다. 
```python
get_etf_trading_volume_and_value("20220908", "20220916")
```

KRX 웹페이지의 `[13106] 투자자별 거래실적` 메뉴에서 `기간 합계` 데이터를 스크래핑합니다. 
```python
get_etf_trading_volume_and_value("20220908", "20220916", "거래대금", "순매수")
```

KRX 웹페이지의 `[13107] 투자자별 거래실적(개별종목)` 메뉴에서 `기간 합계` 데이터를 스크래핑합니다. 
```python
get_etf_trading_volume_and_value("20220908", "20220916", "069500")
```

KRX 웹페이지의 `[13107] 투자자별 거래실적(개별종목)` 메뉴에서 `일별 추이` 데이터를 스크래핑합니다. 
```python
get_etf_trading_volume_and_value("20220908", "20220916", "069500", "거래대금", "순매수")
```

아직 pypi에 업데이트 되지는 않았습니다.

**Comment by woowjs** [comment]
혹 가능하시면 상세보기도 지원을 해 주셨으면 좋겠습니다. 항상 감사드립니다.

**Comment by mr-yoo** [comment]
ETF 개별종목의 일자별 데이터 API는 정상 동작하므로 이슈는 close합니다.
