### ISSUE TITLE
 ValueError: could not convert string to float: '-'

### ISSUE THREAD

**Issue by asjgi** [sharebook-kr/pykrx#134]
[/usr/local/lib/python3.7/dist-packages/pykrx/stock/stock_api.py](https://localhost:8080/#) in get_index_price_change_by_ticker(fromdate, todate, market)
   1678     todate = get_nearest_business_day_in_a_week(todate)
   1679 
-> 1680     return krx.get_index_price_change_by_ticker(fromdate, todate, market)
   1681 
   1682
[/usr/local/lib/python3.7/dist-packages/pykrx/website/comm/util.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
      6     def wrapper(*args, **kwargs):
      7         try:
----> 8             return func(*args, **kwargs)
      9         except (AttributeError, KeyError, TypeError) as e:
     10             logging.info(args, kwargs)

[/usr/local/lib/python3.7/dist-packages/pykrx/website/krx/market/wrap.py](https://localhost:8080/#) in get_index_price_change_by_ticker(fromdate, todate, market)
    968         "등락률": np.float16,
    969         "거래량": np.int64,
--> 970         "거래대금": np.int64
    971     })
    972     return df

종종 잘 사용하고 있어 항상 감사하게 생각합니다. 
헌데 최근 호출에 문제가 있어 이렇게 이슈를 작성 드립니다.

코스피 경우에는 별문제 없이 잘 호출 하는데
코스닥 경우에는 convert string to float 문제가 발생하고 있습니다.
동일하게 코스피 코스닥 돌려서 실행해 보았는데
코스닥만 에러가 발생하는 것 보니 내부 Convert시에 에러가 발생하는데 혹시 수정이 가능할지 여쭤봅니다.

`
!pip install pykrx==1.0.38
!pip install pandas==1.3.5
from pykrx import stock
from datetime import date, datetime, timedelta

today = datetime.now()
today_dt = today.strftime('%Y%m%d')
before_ninety = today + timedelta(days=-90)
before_ninety_dt = before_ninety.strftime('%Y%m%d')
kosdaq_1q_before_df = stock.get_index_price_change_by_ticker(before_ninety_dt, today_dt, "KOSDAQ")
print(kosdaq_1q_before_df)
`

Hoxy 최근 릴리즈된 Pandas에 Dependency가 있는가 해서 이전 버전으로 
버전까지 명시하였지만 동일하게 중간에 에러가 발생하네요 ㅠㅠ

**Comment by asjgi** [comment]
피드백이 없어서 댓글 남깁니다. 수정은 언제 쯤 될까요?

**Comment by mr-yoo** [comment]
제가 요즘 시간이 없어서 바로 대응하기가 어렵네요. 모듈의 수정이 가능하시다면 pull request 날려주셔도 됩니다.

**Comment by asjgi** [comment]
시간 내어 한번 작업해볼께요 ^^ 답변 감사합니다

**Comment by asjgi** [comment]
주말에 소스코드를 좀 봤는데요. KRX에서 받아서 들어오는 데이터 포멧 자체가 KOSPI와 KOSDAQ이 차이점이 있는 듯 합니다.
그렇다면 지금 string to float에러가 나는 이유가 KOSPI일때는 float 형식 그대로 들어오지만 KOSDAQ으로 데이터를 받을때 String으로 들어와
제대로 포팅 안되는 이슈인 듯 해요. 그럼 둘다 String으로 한번싸주거나 포멧처리가 필요할 듯 합니다. 어떻게 진행하는게 좋을까요?

**Comment by asjgi** [comment]
제가 로컬에서 확인해보고 branch 하나 따서 작업하고 Push하려고 하니 
"remote: Permission to sharebook-kr/pykrx.git denied to asjgi.
fatal: unable to access 'https://github.com/sharebook-kr/pykrx.git/': 
The requested URL returned error: 403"
접근 권한이 없네요 ;;

pykrx/pykrx/website/krx/market/wrap.py 해당파일에 967 line에 
df = df.replace('-', 0) 해당 코드 한줄만 입력하면 됩니다 :)
로컬에서는 잘 동작하는 것 확인 하였습니다.
<img width="599" alt="image" src="https://user-images.githubusercontent.com/6354767/210601559-ae97b896-8474-476e-84cb-1ec5f4785a1a.png">

**Comment by mr-yoo** [comment]
@asjgi 
여기엔 제가 할게요^^. 감사합니다
최신 소스코드 반영해서 생성 완료했습니다.
