### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by him1532** [sharebook-kr/pykrx#138]
python 3.10.8 에서 pip install로 pykrx설치후 아래 와 같은 에러가 나네요.
jupyter에서는 실행을 못시키나요?0

import pykrx
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/4c/y4y5b4vn1l152lry_kqhw0d00000gn/T/ipykernel_61810/3292148689.py in <module>
----> 1 import pykrx
ModuleNotFoundError: No module named 'pykrx'

**Comment by ysnrgo** [comment]
python 3.10.1에서도 똑같은 에러가 나네요.

from pykrx import stock
  File "C:\Users\YYS_PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pykrx\__init__.py", line 2, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by ysnrgo** [comment]
> python 3.10.8 에서 pip install로 pykrx설치후 아래 와 같은 에러가 나네요. jupyter에서는 실행을 못시키나요?0
> 
> import pykrx ModuleNotFoundError Traceback (most recent call last) /var/folders/4c/y4y5b4vn1l152lry_kqhw0d00000gn/T/ipykernel_61810/3292148689.py in ----> 1 import pykrx ModuleNotFoundError: No module named 'pykrx'

python3 -m pip install pykrx 로 하고 나서 한번 해보세요.
