### ISSUE TITLE
ticker와 함께 업종 분포가 리턴되면 좋겠는데 혹시 불필요할까요?

### ISSUE THREAD

**Issue by sml8648** [sharebook-kr/pykrx#139]
좋은 라이브러리 만들어 주셔서 감사합니다.
개인적으로 종목마다 업종 분류가 있었으면 좋겠는데 해당 기능이 현재는 없는것 같아서요

다른 이유가 있을까요 구현이 안되어있으면 pr을 날려도 좋을까요?
get_market_ticker_and_name 함수에 같이 리턴되면 좋을것 같습니다.

**Comment by mr-yoo** [comment]
우선 기존 메서드와 카테고리가 다른것 같아서, 필요하다면 다른 함수로 분리해야할 것같아요. 그리고 이 정보를 krx 웹사이트 어디서 얻을 수 있는지 알아야 할 것 같아요.

**Comment by sml8648** [comment]
안녕하세요 답장주셔서 감사합니다. krx의 기본통계 -> 주식 -> 세부안내 -> 업종분류 현황에 업종이 나와있어서 유용하지 않나 생각했습니다. ticker 정보도 같이 있으니 기존 함수에 포함해도 될 것 같았으나, 다시 보니 업종분류가 너무 러프해서 그다지 유용하지는 않을 것 같습니다. 추후에 WICS 업종분류 정보가 활용가능하게 되면 다시 건의드리겠습니다.
