### ISSUE TITLE
get_market_cap 함수가 작동이 안된것 같습니다..

### ISSUE THREAD

**Issue by changhwe** [sharebook-kr/pykrx#141]
stock.get_market_cap("20210104", "20210108", "005930")

**Comment by mr-yoo** [comment]
`get_market_ohlcv_by_date` 메서드를 수정하면서 생긴 side effect 입니다. 다음 commit에서 잘못된 함수 호출 문제(adjust 파라미터를 추가)를 해결합니다. 
- b4eca9b36f841981487ebf46c5e31eb20c8ab250

**Comment by mr-yoo** [comment]
`pip`도 1.0.41 버전으로 업데이트 했습니다.
