### ISSUE TITLE
JSONDecodeError: [Errno Expecting value] 

### ISSUE THREAD

**Issue by WOOJOONSIK** [sharebook-kr/pykrx#146]
from pykrx import stock
stock.get_market_ticker_name("005930")

몇칠전 부터  회사컴, 집컴 동일한 에러가 발생 하네요. 

pykrx  삭제후 다시 설치 pykrx-1.0.41 해도 마찬가지. 

데이터 수집 때문에 막힌건가요?? 

저만 그런건지.   
ㅠㅠ

**Comment by mr-yoo** [comment]
빈번하게 호출해서 웹사이트에서 차단하지 않았을 까요? 구글 코랩에서 테스트해봤을 때 정상적으로 삼성전자가 출력됩니다.

**Comment by WOOJOONSIK** [comment]
감사합니다.  구글 코랩에서 테스트를 생각 못했네요. 
차단 풀리기를 기다려봐야 겠네요.  ㅠㅠ

**Comment by hermian** [comment]
보통 차단 얼마만에 풀리나요? 별로 자주 안하는데...ㅜㅜ

**Comment by mr-yoo** [comment]
#151에 답변을 달아 주셨네요.
