### ISSUE TITLE
데이터 읽을 때 기간에 따른 오류 발생. json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by rmfotjanj1234** [sharebook-kr/pykrx#148]
from pykrx import stock

start = "20000101"
end = "20230512"
ticker = "005930"

df = stock.get_market_ohlcv(start, end, ticker, adjusted=True)
print(df)

위 코드 실행 시 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 이런 에러가 발생합니다.

하지만 여기서 기간을 변경하여
from pykrx import stock

start = "20230501"
end = "20230512"
ticker = "005930"

df = stock.get_market_ohlcv(start, end, ticker, adjusted=True)
print(df)

이렇게 수정하여 실행하면 정상적으로 동작합니다.

지난주만해도 잘 실행됐던 코드인데 갑자기 막히니 당황스럽네요..ㅠㅠ
좋은 라이브러리 만들어 주셔서 감사하게 사용하고 있습니다!

**Comment by keunsoopark** [comment]
저도 stock.get_index_fundamental 함수에서 같은 에러가 뜹니다. 데이터 소스에 변경이 있는걸까요?

**Comment by rmfotjanj1234** [comment]
정확한 에러 메세지는 이렇습니다.

============================================================
File "C:\Anaconda3\lib\site-packages\pykrx\stock\stock_api.py", line 1427, in get_index_ohlcv_by_date
    df = krx.get_index_ohlcv_by_date(fromdate, todate, ticker)
  File "C:\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 8, in wrapper
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\pykrx\website\krx\market\wrap.py", line 819, in get_index_ohlcv_by_date
    df = 개별지수시세().fetch(ticker[1:], ticker[0], fromdate, todate)
  File "C:\Anaconda3\lib\site-packages\pykrx\website\krx\market\core.py", line 765, in fetch
    result = self.read(indIdx2=ticker, indIdx=group_id, strtDd=fromdate,
  File "C:\Anaconda3\lib\site-packages\pykrx\website\krx\krxio.py", line 24, in read
    return resp.json()
  File "C:\Anaconda3\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
======================================================

keunsoopark님 말씀처럼 데이터 구조에 변경이 있는건가 생각이 들긴합니다

**Comment by coolmintmild** [comment]
저도 동일한 에러가 어제부터 발생합니다. 어제 저녁부터 그랬습니다. 오후에는 괜찮았단거 같네요.
제가 확인해본 바로는 2년치 데이터만 불러올수가 있습니다. 

stock.get_market_ohlcv_by_date('20210501', '20210501', '00080')
이건 되는데
 stock.get_market_ohlcv_by_date('20210430', '20210501', '00080')
이건 안됩니다.

**Comment by coolmintmild** [comment]
확인해보니까 KRX 홈페이지가 2년이상 조회가 안되게 바꿨네요...?

"조회기간이 2년을 초과할 수 없습니다." 이렇게 뜨네요 -_-

**Comment by rmfotjanj1234** [comment]
아하 krx 홈페이지에서 자체적으로 막은거군요ㅠㅠ
시간 텀 두고 2년씩 조회해야하나 싶네요...

**Comment by Jehoshaphat-kr** [comment]
yfinance 라이브러리로 접근했을 때도 동일한 오류가 발생하는 것으로 보아 한국거래소 측에서 막은 것이 확실한 것 같네요.. 개선해줄지 ㅠㅠ 
+) pykrx 팀 최고입니다. 복받으실거에욤.. 들숨에 재력, 날숨에 건강!!

**Comment by woowjs** [comment]
2년단위로 ohlcv 값을 읽어보니 예전 정보(예 삼성전자 2018 이전) 수정주가를 가져올 수 없네요.

**Comment by mr-yoo** [comment]
별다른 이슈 없으므로 close합니다.
