### ISSUE TITLE
KOSDAQ 데이터가 반환되지 않음

### ISSUE THREAD

**Issue by jeebok** [sharebook-kr/pykrx#15]
변수에 "KOSDAQ", "KSQ", "코스닥" 무엇을 집어 넣어도, 코스피 데이터가 반환되는 것을 여러 함수에서 확인하였습니다.

**Comment by mr-yoo** [comment]
기본적으로 KOSDAQ / KOSPI 형태로 market 정보를 입력하도록 API가 구성돼 있습니다. 
일부 API를 확인하면 KOSDAQ 정보에서 결측값이 반환되어 에러가 발생하고 있습니다. 
전체 API에 대해 테스트를 추가해 볼게요.

**Comment by mr-yoo** [comment]
다음 함수들이 제대로 동작하지 않아 수정했습니다. 
+ get_market_trading_volume_by_date
+ get_market_trading_value_by_date
+ get_shorting_investor_volume_by_date

445408f175e64f1fc89d0589ba6fbba20e82cb09

유닛 테스트를 시간 날때 마다 추가해서 coverage를 높여볼게요.
사용하시다가 동작하지 않는 API가 있으면 편하게 알려주세요.
