### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by bom1215** [sharebook-kr/pykrx#156]
```
market = 'KOSPI'
date = datetime.today() - timedelta(1) #전일 기준
year_ago_date = date - relativedelta(years=1)
delist_stocks = stock.get_market_price_change(year_ago_date,date,market=market, delist=True)
```

위와 같이 코드를 입력하였더니 아래와 같은 에러가 발생했습니다. 

**AttributeError: 'DataFrame' object has no attribute 'append'**

**Comment by bom1215** [comment]
알아보니 판다스 2.0 (April 3, 2023)부터 append가 없어졌다고 합니다. 
아래는 해당 내용 링크입니다.

https://pandas.pydata.org/docs/whatsnew/v2.0.0.html

**Comment by carpei76** [comment]
그렇군요. 저도 동일한 오류를 발견해서 report하러 왔더니 벌써 하셨네요^^
빨리 수정되면 좋겠네요... ㅠㅠ
pykrx 이 라이브러리 때문에 코드를 쉽게 짤 수 있어서 애용하고 있습니다. 늘 감사드려요~

**Comment by mr-yoo** [comment]
merge 했습니다. 감사합니다.
