### ISSUE TITLE
E3 API가 작동되지 않습니다.

### ISSUE THREAD

**Issue by lyy9257** [sharebook-kr/pykrx#16]
매뉴얼대로 코드를 넣어도 데이터를 불러오지 못하고
빈 데이터프레임을 반환하고 있습니다.

**Comment by mr-yoo** [comment]
`pip install -U pykrx` 업데이트 하고 확인 부탁드립니다.

```pykrx
import pykrx
print(pykrx.__version__)
```

```
0.1.26
```

**Comment by mr-yoo** [comment]
추가 문의 및 문제가 재현된다면 reopen 해주세요.
피드백 감사합니다.
