### ISSUE TITLE
AttributeError: module 'pykrx.stock' has no attribute 'get_stock_ticker_list' 문의

### ISSUE THREAD

**Issue by RyanKor** [sharebook-kr/pykrx#166]
`Readme.md`에 올라와 있는 예제 실행 중 `get_stock_ticker_list`가 없어 문의드립니다.

실행한 소스코드는 아래와 같습니다.

```python
import time
for ticker in stock.get_stock_ticker_list():
    df = stock.get_market_ohlcv("20181210", "20181212", ticker)
    print(df.head())
    time.sleep(1)
```

발생한 에러는 아래와 같습니다.

```bash
    for ticker in stock.get_stock_ticker_list():
AttributeError: module 'pykrx.stock' has no attribute 'get_stock_ticker_list'
```

이슈에 `get_stock_ticker_list`라는 메서드 관련 문의가 없어서 잘 실행되는 코드인데, 제가 버전을 잘못 설치했나 싶어서 `0.1.17`, `1.0.26`, `1.0.33` 버전으로 최신 버전을 지우고 설치해봤으나, 동일한 에러가 발생하여 메소드가 구현 안된 것으로 보입니다.

깃헙 이슈에 다른 분들 문의 사항도 `get_stock_ticker_list` 키워드로 오픈된 것과 클로즈된 것 모두 찾아봤는데 문의 사항이 없는 것 같습니다.

혹시 다른 메서드로 이름이 치환되었는지도 문의드립니다.

감사합니다.

**Comment by mr-yoo** [comment]
다음 함수를 호출해 주세요.
```python
get_market_ticker_list
```
사용할 수 있는 ticker_list는 자동완성 기능으로 확인할 수 있어요.
![image](https://github.com/sharebook-kr/pykrx/assets/29349211/cbdafdcb-b5d5-445b-92c6-5f255f0e26e9)

**Comment by seungtaekim-q** [comment]
![Screenshot from 2023-08-30 10-24-25](https://github.com/sharebook-kr/pykrx/assets/104345910/56dfa5fe-3e17-4f72-b19e-f3a609c4700a)

`Readme.md` 에 사용 예제 변경해주셔야 될 것 같습니다 ~ `get_stock_ticker_list` 메소드로 안내하고 있어서요
