### ISSUE TITLE
get_shorting_balance_by_ticker - 일자 딜레이가 있나요?

### ISSUE THREAD

**Issue by yapyada** [sharebook-kr/pykrx#169]
df = stock.get_shorting_volume_by_ticker('20230922')

9월25일 13시 기준 get_shorting_volume_by_ticker는 데이터가 잘 나오는데 

df = stock.get_shorting_balance_by_ticker('20230922')

get_shorting_balance_by_ticker는 빈 데이터프레임을 리턴해서 여쭤봅니다

**Comment by mr-yoo** [comment]
`get_shorting_volume_by_ticker`는 개별종목 공매도 거래 내역으로 서버가 아무런 결과를 주지 않습니다. 

![image](https://github.com/sharebook-kr/pykrx/assets/29349211/7b34aff5-75d1-4843-89bd-56e0696542df)

`get_shorting_balance_by_ticker`는 개별종목 공매도 순보유잔고로 다음과 같습니다.

![image](https://github.com/sharebook-kr/pykrx/assets/29349211/d7798b6c-fb7d-4b2f-bb5a-2d8457d69a80)

즉, 서버가 전달하는 데이터가 달라서 다른 결과가 나옵니다.
