### ISSUE TITLE
검색이 안되는 종목들이 있습니다.

### ISSUE THREAD

**Issue by loopinf** [sharebook-kr/pykrx#17]
'3노드디지탈', '코웰이홀딩스', '에스앤씨엔진그룹', '오가닉티코스메틱', '헝셩그룹', '네프로아이티',
       '로스웰', '성융광전투자', '차이나그레이트', 'GRT', '윙입푸드', '이스트아시아홀딩스', '컬러레이',
       '완리', '웨이포트', '차이나하오란', '연합과기', '범화건설', '중국고섬', '울산실업', '평산차업',
       'SBI모기지', '중국원양자원'

이런 종목들은 검색이 안됩니다.

**Comment by mr-yoo** [comment]
3노드디지탈, 코웰이홀딩스 등 상장 폐지 종목은 조회되지 않습니다. 

상장 폐지 종목이 아닌 `오가닉티코스메틱 (900300)` 같은 경우에는 다음 코드로 정상 조회됩니다.
```python
from pykrx import stock
df = stock.get_market_ohlcv_by_date("20200101", "20200107", "900300")
print(df)
```

**Comment by mr-yoo** [comment]
추가 문의가 있으시면 issue를 reopen 해주세요.
피드백 감사합니다.

**Comment by mr-yoo** [comment]
상장 폐지 종목 이외에도 검색이 안되는 항목이 존재하는 것을 확인합니다. 
조금 더 자세히 봤어야 하는데,,, 다른 이슈(https://github.com/sharebook-kr/pykrx/issues/3) 를 해결하다 발견했습니다.

**Comment by mr-yoo** [comment]
모듈을 업데이트 한 후에 다음과 같이 확인할 수 있습니다. 

```python
from pykrx import stock

tickers = stock.get_market_ticker_list()
for ticker in tickers:
    name = stock.get_market_ticker_name(ticker)
    print(tickers, name)
```

```text
095570 AJ네트웍스
006840 AK홀딩스
027410 BGF
282330 BGF리테일
138930 BNK금융지주
001460 BYC
......
```
