### ISSUE TITLE
갑자기 함수에서 아무런 return이 나오지 않습니다.

### ISSUE THREAD

**Issue by noblessnomad** [sharebook-kr/pykrx#172]
어제까지만 해도 문제 없이 잘 사용하고 있었는데요. 오늘 코드를 돌리니 get_previous_business_day, get_market_ticker_list 등에서 아무런 return 값도 나오질 않습니다.

**Comment by mr-yoo** [comment]
테더링, 와이파이 등을 변경하고 테스트해 보세요. 과도한 요청으로 서버에서 IP를 차단했을 수 있습니다.
