### ISSUE TITLE
동일한 method 호출에 대해서 어떤 경우에는 Empty DataFrame이 응답됩니다.

### ISSUE THREAD

**Issue by jays1204** [sharebook-kr/pykrx#173]
안녕하세요.
아래와 같은 코드를 실행하면 응답값이 잘오는데 간혹가다가 Empty DataFrame이 응답됩니다. 한번 Empty DataFrame이 응답되면 일정시간동안에는 계속 Empty DataFrame이 응답되는데 원인을 알 수 있을까요?
krx(https://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd)에 자주 접근하는 경우 krx에서 어느정도 시간동안 호출을 제한하는걸로 보이는데 이와 같을 경우에 Empty DataFrame이 응답되는걸까요?

```python
from pykrx import stock

df = stock.get_market_ohlcv('20240102', '20240103', '009070', adjusted=False)
print(df)
```

**Comment by mr-yoo** [comment]
과도한 호출로 인해 IP가 차단된 것으로 보입니다. 반복문 사용 시 time.sleep( ) 함수로 적당 수준 쉬었다가 호출해야 할 것 같습니다.
