### ISSUE TITLE
stock.get_market_ohlcv_by_date 거래대금 누락

### ISSUE THREAD

**Issue by haneol815** [sharebook-kr/pykrx#177]
안녕하세요. 
pykrx코드를 감사히 잘 사용하고 있습니다. 

어느 날 부터인가 stock.get_market_ohlcv_by_date를 동일하게 사용중인데 "거래대금" 항목이 더이상 수집되지 않는 것을 발견했습니다. 
1. df = stock.get_market_ohlcv_by_date(start_date, end_date, stock_code,adjusted=True)
2. df = stock.get_market_ohlcv_by_date(start_date, end_date, stock_code,adjusted=False)
"1."의 수정주가의 경우 거래대금이 포함되지 않고, 
"2."의 수정주가가 아닌 경우 거래대금이 포함된다는 것을 알았습니다. 

저는 수정주가와 거래대금 모두가 필요한 상황입니다. 

제안사항은 **거래대금을 두 경우 모두 포함되게** 원래대로(원래 포함이었다고 생각합니다.) **되돌려 주시면 안될지요?**

**Comment by mr-yoo** [comment]
꽤 오래전 krx가 단기간의 수정주가만을 제공해서 데이터를 가져올 수 없게 됐습니다. 그래서수정주가의 경우 naver에서 값을 가져오고 있습니다. 그래서 결과적으로 수정주가 사용 여부에 따라 데이터 형식이 조금 다르구요.
