### ISSUE TITLE
데이터를 받아오지 못합니다.

### ISSUE THREAD

**Issue by lyy9257** [sharebook-kr/pykrx#18]
pykrx를 돌렸을때 데이터를 받아오지 못합니다.

---에러 발생현황---
File "G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\korea_data.py", line 186, in <module>
    routine = Routine()
  File "G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\korea_data.py", line 109, in __init__
    self.get = krx.Get()
  File "G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\product_info\api\krx.py", line 23, in __init__
    self.stock_code_list = stock.get_market_ticker_list(self.today)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\stock\api.py", line 48, in get_market_ticker_list
    return krx.get_stock_ticker_list(date)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 118, in get_stock_ticker_list
    stock = _StockTicker()
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 24, in __init__
    super(class_w, self).__init__(*args, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 45, in __init__
    df_listed = self._get_stock_info_listed()
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 65, in _get_stock_info_listed
    df = _StockFinder().fetch(market)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 21, in fetch
    result = self.post(mktsel=market, searchText=name)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\krxio.py", line 17, in post
    return resp.json()
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(base) G:\>python G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\korea_data.py
20200827
Traceback (most recent call last):
  File "G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\korea_data.py", line 186, in <module>
    routine = Routine()
  File "G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\korea_data.py", line 109, in __init__
    self.get = krx.Get()
  File "G:\Develop\MyBetaPortfolio\mybetaportfolio_backend\product_info\api\krx.py", line 23, in __init__
    self.stock_code_list = stock.get_market_ticker_list(self.today)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\stock\api.py", line 48, in get_market_ticker_list
    return krx.get_stock_ticker_list(date)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 118, in get_stock_ticker_list
    stock = _StockTicker()
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 24, in __init__
    super(class_w, self).__init__(*args, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 45, in __init__
    df_listed = self._get_stock_info_listed()
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\comm\util.py", line 7, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 65, in _get_stock_info_listed
    df = _StockFinder().fetch(market)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py", line 21, in fetch
    result = self.post(mktsel=market, searchText=name)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\pykrx\website\krx\krxio.py", line 17, in post
    return resp.json()
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\simplejson\decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "C:\Users\dldjs\Anaconda3\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

*입력날짜는 YYYYMMDD 형식으로 입력했습니다.

---- 설치된 패키지 리스트
alabaster==0.7.12
anaconda-client==1.7.2+6.g6d462d5
anaconda-navigator==1.9.12
anaconda-project==0.8.3
aniso8601==8.0.0
argh==0.26.2
asgiref==3.2.7
asn1crypto==1.3.0
astroid==2.3.3
astropy==4.0
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.4.4
awsebcli==3.18.2
Babel==2.8.0
backcall==0.1.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.7
beautifulsoup4==4.9.1
bitarray==1.2.1
bkcharts==0.2
bleach==3.1.0
bokeh==1.4.0
boto==2.49.0
botocore==1.15.49
Bottleneck==1.3.2
bs4==0.0.1
cement==2.8.2
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
click-plugins==1.1.1
cligj==0.5.0
cloudpickle==1.3.0
clyent==1.2.2
colorama==0.4.3
comtypes==1.1.7
conda==4.8.2
conda-build==3.18.11
conda-package-handling==1.6.0
conda-verify==3.4.2
contextlib2==0.6.0.post1
cryptography==2.9.2
cycler==0.10.0
Cython==0.29.15
cytoolz==0.10.1
dask==2.11.0
DateTime==4.3
decorator==4.4.1
defusedxml==0.6.0
Deprecated==1.2.10
diff-match-patch==20181111
distributed==2.11.0
Django==3.0.7
django-cors-headers==3.4.0
django-debug-toolbar==2.2
django-rest-framework==0.1.0
djangorestframework==3.11.0
docutils==0.15.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock==3.0.12
finance-datareader==0.9.6
flake8==3.7.9
Flask==1.1.2
Flask-RESTful==0.3.8
fsspec==0.6.2
future==0.16.0
gevent==1.4.0
gitdb==4.0.5
GitPython==3.1.2
glob2==0.7
greenlet==0.4.15
h5py==2.10.0
HeapDict==1.0.1
html5lib==1.0.1
hypothesis==5.5.4
idna==2.7
iexfinance==0.4.3
imageio==2.6.1
imagesize==1.2.0
importlib-metadata==1.5.0
install==1.3.3
intervaltree==3.0.2
ipykernel==5.1.4
ipython==7.12.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jdcal==1.4.1
jedi==0.14.1
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.14.1
json5==0.9.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.1
jupyterlab==1.2.6
jupyterlab-server==1.0.6
keyring==21.1.0
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
libarchive-c==2.8
llvmlite==0.31.0
locket==0.2.0
lxml==4.5.2
MarkupSafe==1.1.1
matplotlib==3.2.1
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
mock==4.0.1
more-itertools==8.2.0
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
multitasking==0.0.9
munch==2.5.0
mysql-connector-python==8.0.20
mysqlclient==2.0.1
navigator-updater==0.2.1
nbconvert==5.6.1
nbformat==5.0.4
networkx==2.4
nltk==3.4.5
nose==1.3.7
notebook==6.0.3
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
numpydoc==0.9.2
ogr==0.12.0
olefile==0.46
openpyxl==3.0.3
packaging==20.1
panda==0.3.1
pandas==1.0.3
pandas-datareader==0.9.0
pandocfilters==1.4.2
paramiko==2.7.1
parmap==1.5.2
parso==0.5.2
partd==1.1.0
path==13.1.0
pathlib2==2.3.5
pathspec==0.5.9
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
pluggy==0.13.1
ply==3.11
prometheus-client==0.7.1
prompt-toolkit==3.0.3
psutil==5.6.7
psycopg2==2.8.5
py==1.8.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.20
pycrypto==2.6.1
pycurl==7.43.0.5
pydocstyle==4.0.1
pyflakes==2.1.1
PyGithub==1.51
Pygments==2.5.2
PyJWT==1.7.1
pykrx==0.1.26
pylint==2.4.4
PyMySQL==0.9.3
PyNaCl==1.3.0
pyodbc===4.0.0-unsupported
pyOpenSSL==19.1.0
pyparsing==2.4.7
pypiwin32==223
pyreadline==2.1
pyrsistent==0.15.7
PySocks==1.7.1
pytest==5.3.5
pytest-arraydiff==0.3
pytest-astropy==0.8.0
pytest-astropy-header==0.1.2
pytest-doctestplus==0.5.0
pytest-openfiles==0.4.0
pytest-remotedata==0.3.2
python-dateutil==2.8.0
python-gitlab==2.2.0
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
python-polylabel==0.6
pytz==2020.1
PyWavelets==1.1.1
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.3.1
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.20.1
requests-file==1.5.1
rope==0.16.0
Rtree==0.9.4
ruamel-yaml==0.15.87
scikit-image==0.16.2
scikit-learn==0.22.1
scipy==1.4.1
seaborn==0.10.0
semantic-version==2.5.0
Send2Trash==1.5.0
Shapely==1.7.0
simplegeneric==0.8.1
simplejson==3.17.2
singledispatch==3.4.0.3
six==1.11.0
smmap==3.0.4
snowballstemmer==2.0.0
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==2.0.1
Sphinx==2.4.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.2.0
spyder==4.0.1
spyder-kernels==1.8.1
SQLAlchemy==1.3.17
sqlparse==0.3.1
statsmodels==0.11.0
sympy==1.5.1
tables==3.6.1
tblib==1.6.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
toolz==0.10.0
tornado==6.0.3
tqdm==4.42.1
traitlets==4.3.3
ujson==1.35
unicodecsv==0.14.1
urllib3==1.24.3
watchdog==0.10.2
wcwidth==0.1.8
webencodings==0.5.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
win-inet-pton==1.1.0
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.11.2
xlrd==1.2.0
XlsxWriter==1.2.7
xlwings==0.17.1
xlwt==1.3.0
xmltodict==0.12.0
yahoo-finance==1.4.0
yahoofinancials==1.5
yapf==0.28.0
yfinance==0.1.54
zict==1.0.0
zipp==2.2.0
zope.interface==5.1.0

**Comment by mr-yoo** [comment]
우선 GUI 코드 없이 아래 코드만을 사용해도 에러가 발생하나요?

```python
from pykrx import stock
stock.get_market_ticker_list("20200827")
```

**Comment by lyy9257** [comment]
@mr-yoo 
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-2-7b278d1451b9> in <module>
      1 from pykrx import stock
----> 2 stock.get_market_ticker_list("20200827")

~\Anaconda3\lib\site-packages\pykrx\stock\api.py in get_market_ticker_list(date)
     46 # -----------------------------------------------------------------------------
     47 def get_market_ticker_list(date=None):
---> 48     return krx.get_stock_ticker_list(date)
     49 
     50 

~\Anaconda3\lib\site-packages\pykrx\website\comm\util.py in wrapper(*args, **kwargs)
      5     def wrapper(*args, **kwargs):
      6         try:
----> 7             return func(*args, **kwargs)
      8         except (AttributeError, KeyError, TypeError):
      9             return DataFrame()

~\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py in get_stock_ticker_list(date)
    116 @dataframe_empty_handler
    117 def get_stock_ticker_list(date=None):
--> 118     stock = _StockTicker()
    119     # 조회 시점에 상장된 종목을 반환
    120     cond = stock.df['상폐일'].isnull()

~\Anaconda3\lib\site-packages\pykrx\website\comm\util.py in __init__(self, *args, **kwargs)
     22             if self._sealed:
     23                 return
---> 24             super(class_w, self).__init__(*args, **kwargs)
     25             self._sealed = True
     26     class_w.__name__ = class_.__name__

~\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py in __init__(self)
     43     def __init__(self):
     44         # 조회일 기준의 상장/상폐 종목 리스트
---> 45         df_listed = self._get_stock_info_listed()
     46         df_delisted = self._get_stock_info_delisted()
     47         self.df_delisted = df_delisted                ## DEBUG !!

~\Anaconda3\lib\site-packages\pykrx\website\comm\util.py in wrapper(*args, **kwargs)
      5     def wrapper(*args, **kwargs):
      6         try:
----> 7             return func(*args, **kwargs)
      8         except (AttributeError, KeyError, TypeError):
      9             return DataFrame()

~\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py in _get_stock_info_listed(self, market)
     63         """
     64         market = {"코스피": "STK", "코스닥": "KSQ", "코넥스": "KNX", "전체": "ALL"}.get(market, "ALL")
---> 65         df = _StockFinder().fetch(market)
     66         df.rename(columns = {'full_code': 'ISIN', 'short_code': '티커', 'codeName': '종목', 'marketName': '시장'}, inplace=True)
     67         # - 증권(7)과 사용자 영역 선택

~\Anaconda3\lib\site-packages\pykrx\website\krx\market\ticker.py in fetch(self, market, name)
     19         :return      : 종목 검색 결과 DataFrame
     20         """
---> 21         result = self.post(mktsel=market, searchText=name)
     22         return DataFrame(result['block1'])
     23 

~\Anaconda3\lib\site-packages\pykrx\website\krx\krxio.py in post(self, **params)
     15         params.update({"code": otp.text})
     16         resp = super().read(**params)
---> 17         return resp.json()
     18 
     19     @property

~\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

~\Anaconda3\lib\site-packages\simplejson\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    523             parse_constant is None and object_pairs_hook is None
    524             and not use_decimal and not kw):
--> 525         return _default_decoder.decode(s)
    526     if cls is None:
    527         cls = JSONDecoder

~\Anaconda3\lib\site-packages\simplejson\decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

~\Anaconda3\lib\site-packages\simplejson\decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

네 오류가 발생합니다.(jupyter notebook에서 테스트)

**Comment by mr-yoo** [comment]
`pip freeze` 명령으로 의존성 목록을 작성 부탁드립니다. 
번거롭겠지만 다시 한 번 요청드립니다.
