### ISSUE TITLE
get_market_ticker_list

### ISSUE THREAD

**Issue by 0x68756d8616e6f69664** [sharebook-kr/pykrx#190]
제목의 함수가 제대로 동작하지 못 해 티커를 못 불러오는 것 같아요.

**Comment by yiugn** [comment]
https://github.com/sharebook-kr/pykrx/pull/188

https://github.com/sharebook-kr/pykrx/pull/188/files

**Comment by mr-yoo** [comment]
최근 KRX 웹페이지가 개편됨에 따라 스크래핑 코드에 Refer 값을 추가했습니다. 
- 3c4bdd50, 2bb4b1ae 

모듈 업데이트 후 동작 확인해 주세요.
