### ISSUE TITLE
pykrx 오류 관련. 

### ISSUE THREAD

**Issue by WOOJOONSIK** [sharebook-kr/pykrx#197]
어제 부터 pykrx가 작동을 안하네요. 

data.krx.co.kr 사이트가 죽어 있어서 발생하는 문제인듯.. 

언제나 정상화 시켜 줄려나..  

괜히 이것 저것 테스트 안하셔도 될듯.  

저는 한국거래소에 문의 결과. 

사이트가 죽은게 아닌  제 ip가 차단 된거라네요.    ㅠㅠ

**Comment by mr-yoo** [comment]
site가 개편 중인가봐요. 점검을 해볼게요.
