### ISSUE TITLE
최근 오류

### ISSUE THREAD

**Issue by atheling44** [sharebook-kr/pykrx#199]
pykrx 라이브러리 사용하여 데이터를 잘 받아왔는데, 7/8일부터 에러가 납니다.
저와 비슷한 오류를 경험하신 붙들이 문의드리는데, 데이터 제공처에서 사용하던 값을 변경한듯 합니다. 
티커 가져오는 함수만을 실행해도 값을 가져왔을때 값이 없다고 뜨네요, 확인부탁드립니다.

**Comment by atheling44** [comment]
krx에서 수정이 되었나보네요, 오늘은 되네요.

**Comment by bankplus** [comment]
저는 아직도 에러나는데요?

**Comment by mr-yoo** [comment]
비슷한 문제를 다음 커밋에서 해결했는데요.  
- 3c4bdd50

사용하신 코드를 알려주시면 확인해 볼게요.

**Comment by bankplus** [comment]
> 비슷한 문제를 다음 커밋에서 해결했는데요.
> 
> * [3c4bdd5](https://github.com/sharebook-kr/pykrx/commit/3c4bdd507c7dba776d1f2be2213a5b938642cc9d)
> 
> 사용하신 코드를 알려주시면 확인해 볼게요.

버전업 다시하고 정리하니까 잘되네요. 감사합니다.
