### ISSUE TITLE
krx쪽 아예 전부 조회가 안되는 것 같습니다. referer인가 추가해봐도 안되는데 다른 분들은 어떻게 해결하셨는지 모르겠네요.

### ISSUE THREAD

**Issue by ParkSangIn** [sharebook-kr/pykrx#202]
referer 추가해도 krx쪽에서 읽어오는 데이터는 전부 안되는 것 같습니다.

stock.get_market_trading_value_by_date()

특히 매수주체별 거래대금도 조회가 안되네요.

isin인가하는 함수에서 계속 빈 데이터프레임 반환하는데 거기다가 삼성전자 isin으로 대체해서 박아 넣어도 문제가 있네요.

**Comment by ParkSangIn** [comment]
7월 14일 오후 10시 40분쯤 부터 갑자기 정상적으로 되네요

**Comment by mr-yoo** [comment]
최신 버전에서 다음 코드로 실행되는 것 확인했어요. 
```
from pykrx import stock
df = stock.get_market_trading_value_by_date("20240101", "20240630", "005930")
```

관련한 수정이 있었으니 모듈 업데이트 해 주세요. 리포팅 감사합니다.

**Comment by mr-yoo** [comment]
참고로 3c4bdd50 에 Refer 헤더 추가했습니다.
