### ISSUE TITLE
함수 파라미터 문제

### ISSUE THREAD

**Issue by Undefined-K** [sharebook-kr/pykrx#23]
get_market_trading_value_and_volume_by_ticker 함수에서
investor 변환 시, "외국인": 9000 이 빠져 있습니다.

그래서 함수를 호출하면
외국인 결과는 0으로 반환하는 에러가 발생합니다.

**Comment by mr-yoo** [comment]
안녕하세요. reporting 감사합니다. 
코드 수정해서 KRX 웹페이지와 같은 결과를 확인했습니다. 

```python
df = stock.get_market_trading_value_and_volume_by_ticker("20200907", investor="외국인")
df.head()
```

<img src="https://user-images.githubusercontent.com/29349211/93222766-43aaf600-f7aa-11ea-8573-9ba2d0516a50.png" width=500 />

<img src="https://user-images.githubusercontent.com/29349211/93223146-b3b97c00-f7aa-11ea-9193-51cebc675fb4.png" width=500 />
