### ISSUE TITLE
It seems that MKD30015 not working since 20200917

### ISSUE THREAD

**Issue by myeongjong-kim** [sharebook-kr/pykrx#25]
It seems that MKD30015 not working since 20200917.

**Comment by mr-yoo** [comment]
`MKD30015` can be called directly as follows:

```python
from pykrx.website.krx.market.core import MKD30015

df = MKD30015().fetch(date="20200917", market="ALL")
df.head()
```
It is recommended to use `stock.get_market_cap_by_ticker` as a user-friendly API.
```python
from pykrx import stock
df = stock.get_market_cap_by_ticker(date="20200917", market="ALL")
```

If you attach the code you wrote, I will check it in detail.

**Comment by mr-yoo** [comment]
In the current version, the **business day** of the stock market should be passed by variable 'B' of 'API'.

**Comment by mr-yoo** [comment]
> targetDayStr="20200917"
> print(stock.get_market_ticker_list("20200921"))
> dfTargetDay = stock.get_market_cap_by_ticker(targetDayStr)
> if (dfTargetDay.empty):
> print('targetDay empty. day: ' + targetDayStr)

It seems to be a version problem or a module dependency problem. Please check PYKRX version first.
```python
import pykrx
print(pykrx.__version__)
```
If the version is lower than `0.1.41`, upgrade to the latest version.
`pip install -U pykrx`


If the latest version does not fix the problem, please attach a list of installed modules that you see as a result of `pip freeze`.

**Comment by myeongjong-kim** [comment]
asgiref==3.2.10
astroid==2.4.2
certifi==2020.6.20
chardet==3.0.4
colorama==0.4.3
comtypes==1.1.7
DateTime==4.3
Django==3.0.8
et-xmlfile==1.0.1
excel2img==1.4.0
idna==2.10
image==1.5.32
isort==4.3.21
jdcal==1.4.1
lazy-object-proxy==1.4.3
mccabe==0.6.1
numpy==1.19.1
openpyxl==3.0.4
pandas==1.0.5
Pillow==7.2.0
pykrx==0.1.41
pylint==2.5.3
pypiwin32==223
PyQt5==5.15.0
PyQt5-sip==12.8.0
python-dateutil==2.8.1
pytz==2020.1
pywin32==228
pywinauto==0.6.8
requests==2.24.0
six==1.15.0
sqlparse==0.3.1
toml==0.10.1
urllib3==1.25.10
wrapt==1.12.1
xlrd==1.2.0
zope.interface==5.1.0

**Comment by mr-yoo** [comment]
The code works well in a virtual environment made from a list of modules you provide.

`$ python --version`
`Python 3.7.6`

> $ virtualenv venv
> $ source venv/Script/activate
> venv $ pip intall -r requirement.txt

I will check the code with the latest Python (version 3.8.4). If it goes well, I think you'd better reinstall Python.

**Comment by mr-yoo** [comment]
It operates normally in the pure python 3.8.4 and the latest Anaconda (3.8.3).
- I tested the codes with python 3.8.4 on `https://repl.it/languages/python3` website and with anaconda on my desktop.

![image](https://user-images.githubusercontent.com/29349211/93919565-d3234c80-fd48-11ea-8b25-b800cc77304b.png)

I don't think there's anything I can help with given information.
