### ISSUE TITLE
전체종목 시세조회의 결과값이 없습니다.

### ISSUE THREAD

**Issue by leeway00** [sharebook-kr/pykrx#30]
df = stock.get_market_ohlcv_by_ticker("20200831")
print(df.head(3))

Empty DataFrame
Columns: []
Index: []

**Comment by mr-yoo** [comment]
버전확인 부탁드립니다. 
```python
import pykrx
print(pykrx.__version__)
```

현재 최신 버전은 `'0.1.42'`  입니다. 

버전이 낮다면 업그레이드 부탁드려요.
`pip install -U pykrx`


------
최신 버전임에도 불구하고 결과가 이상하다면 다음 코드의 실행 결과를 알려주세요. 
```python
from pykrx.website.krx.market.ticker import _StockFinder
s = _StockFinder()
print(s.fetch())
```

**Comment by leeway00** [comment]
'''
JSONDecodeErrorTraceback (most recent call last)
<ipython-input-259-e6244695720c> in <module>
      1 from pykrx.website.krx.market.ticker import _StockFinder
      2 s = _StockFinder()
----> 3 print(s.fetch())

/usr/local/lib/python3.6/dist-packages/pykrx/website/krx/market/ticker.py in fetch(self, market, name)
     18         :return      : 종목 검색 결과 DataFrame
     19         """
---> 20         result = self.post(mktsel=market, searchText=name)
     21         return DataFrame(result['block1'])
     22 

/usr/local/lib/python3.6/dist-packages/pykrx/website/krx/krxio.py in post(self, **params)
     15         params.update({"code": otp.text})
     16         resp = super().read(**params)
---> 17         return resp.json()
     18 
     19     @property

/usr/local/lib/python3.6/dist-packages/requests/models.py in json(self, **kwargs)
    896                     # used.
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 
    900     @property

/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/usr/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
'''

**Comment by leeway00** [comment]
답변 감사합니다.
말씀해주신 코드를 실행시키면 다음과 같은 에러가 납니다.
```
JSONDecodeErrorTraceback (most recent call last)
<ipython-input-259-e6244695720c> in <module>
      1 from pykrx.website.krx.market.ticker import _StockFinder
      2 s = _StockFinder()
----> 3 print(s.fetch())

/usr/local/lib/python3.6/dist-packages/pykrx/website/krx/market/ticker.py in fetch(self, market, name)
     18         :return      : 종목 검색 결과 DataFrame
     19         """
---> 20         result = self.post(mktsel=market, searchText=name)
     21         return DataFrame(result['block1'])
     22 

/usr/local/lib/python3.6/dist-packages/pykrx/website/krx/krxio.py in post(self, **params)
     15         params.update({"code": otp.text})
     16         resp = super().read(**params)
---> 17         return resp.json()
     18 
     19     @property

/usr/local/lib/python3.6/dist-packages/requests/models.py in json(self, **kwargs)
    896                     # used.
    897                     pass
--> 898         return complexjson.loads(self.text, **kwargs)
    899 
    900     @property

/usr/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/usr/lib/python3.6/json/decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

/usr/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mr-yoo** [comment]
이 부분은 단순 requests 요청 부분으로 version과 상관없어야 하는 부분입니다. 
실수로 pykrx 코드를 수정했을 경우 위 문제가 발생할 수 있습니다.

`get_market_ohlcv_by_ticker` 함수는 단순히 다음 내용을 정리한 것에 불과합니다.
다음 내용이 정상실행된다면 pykrx 코드가 오염됐다고 생각할 수 있습니다. 
```python
import requests

# OTP 요청
otp_url = "http://marketdata.krx.co.kr/contents/COM/GenerateOTP.jspx"
header = {"User-Agent": "Mozilla/5.0"}
param = {
    "name": "form",
    "bld": "COM/finder_stkisu"
}
resp = requests.get(otp_url, headers=header, params=param)
otp = resp.text
print(otp)

# 데이터 요청 with OTP
data_url = "http://marketdata.krx.co.kr/contents/MKD/99/MKD99000001.jspx"
data = {
    "mktsel": "ALL",    
    "code": otp
}
resp = requests.post(data_url, headers=header, data=data)
print(resp.text)
```

만약 위코드가 정상실행된다면 **모듈을 삭제 후에 재설치** 하시면 될거에요.
`pip uninstall pykrx`
`pip install pykrx`

위 코드가 실행안된다면 에러 메시지 공유 부탁드리구요.

**Comment by bombs-kim** [comment]
@mr-yoo 
안녕하세요! 조금 다른 질문인데요, 저 같은 경우는
₩₩₩
otp_url = "http://marketdata.krx.co.kr/contents/COM/GenerateOTP.jspx"
header = {"User-Agent": "Mozilla/5.0"}
param = {
    "name": "form",
    "bld": "COM/finder_stkisu"
}
resp = requests.get(otp_url, headers=header, params=param)
otp = resp.text
print(otp)
₩₩₩

이부분에서 403 에러가 납니다. 운영체제는 ubuntu고 pykrx는 최신버젼으로 실행하였습니다. 혹시 이 문제의 해결 방법이 있을까요?

**Comment by mr-yoo** [comment]
@bombs-kim 
코드 자체는 전혀 문제가 없어 보입니다. 
403 에러라면 과도한 요청으로 서버에서 IP를 차단했을 확률이 높습니다. 

IP 변경을 위해 핸드폰으로 테더링하고 코드를 실행 해보시겠어요?

**Comment by bombs-kim** [comment]
@mr-yoo IP 변경시 정상 작동하는 것 확인하였습니다! 도움 주셔서 감사합니다.
