### ISSUE TITLE
krx아이피 차단 해제 방법이 있을까요?

### ISSUE THREAD

**Issue by peacmake** [sharebook-kr/pykrx#31]
어제 데이터를 긁어오는 것을 밤에 실행해놓고 아침에 보니 중간 쯤에서 부터 에러가 나서 확인해 보니
아이피가 차단된 것 같아요.
다른 아이피에서는 데이터를 잘 가져오는데, 해당 장비에서는 데이터를 전혀 못가져오네요.
혹시 어떻게 하면 해제할 수 있는지 알 수 있을지요?

**Comment by mr-yoo** [comment]
다음 페이지에서 민원/상담 요청해서 문의해보셔야 할 것 같습니다. 
`https://voc.krx.co.kr/krx/guide/JHPVOC01011.jsp?siteCode=krx`
IP 주소와 함께 문의해보세요.

----

결과도 알려주시면 감사하겠습니다.

**Comment by peacmake** [comment]
차단되었다가 일정기간이 지나면, 풀렸었다는 경험을 갖고 있다는 분의 이야기가 있어서,
며칠 좀 더 기다려 보고, 상당기간 지난 이후에도 차단이 되어 있으면, 알려주신 방법으로 문의를 해 보도록 하겠습니다.
IP를 바꿀까도 고려하고 있습니다. 어떤 경우든, 변화가 있으면, 다시 글을 남기겠습니다.

**Comment by narirocks** [comment]
40일 정도 있으니까 풀렸던거 같아요 ㅋㅋㅋ

**Comment by peacmake** [comment]
안풀려서, 서버 재계약하면서 IP를 바꾸어 버렸습니다.

**Comment by skarlans** [comment]
이거 제 경험상 krx에서 반복된 request로 5년치 정도 이상 받아오려고 하면 막히는거같아요...
