### ISSUE TITLE
어제까지 잘되던게 안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by hwanys2** [sharebook-kr/pykrx#35]
def today_stock_company():
    global df_stock
    today = stock.get_nearest_business_day_in_a_week()
    df_stock = stock.get_market_ohlcv_by_ticker(today)
    df_stock["종목명"] = df_stock["종목명"].str.upper()
    df_stock = df_stock.reset_index()

today_stock_company()

이걸실행하면

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-10-ea2c0e9098ca> in <module>()
     28     df_stock = df_stock.reset_index()
     29 
---> 30 today_stock_company()
     31 
     32 #### 종목 코드 검색

<ipython-input-10-ea2c0e9098ca> in today_stock_company()
     23 def today_stock_company():
     24     global df_stock
---> 25     today = stock.get_nearest_business_day_in_a_week()
     26     df_stock = stock.get_market_ohlcv_by_ticker(today)
     27     df_stock["종목명"] = df_stock["종목명"].str.upper()

/home/pi/.local/lib/python3.7/site-packages/pykrx/stock/api.py in get_nearest_business_day_in_a_week()
     36     curr = _datetime2string(curr)
     37     prev = _datetime2string(prev)
---> 38     df = krx.get_index_ohlcv_by_date(prev, curr, "1001")
     39     return df.index[-1].strftime("%Y%m%d")
     40 

/home/pi/.local/lib/python3.7/site-packages/pykrx/website/comm/util.py in wrapper(*args, **kwargs)
      5     def wrapper(*args, **kwargs):
      6         try:
----> 7             return func(*args, **kwargs)
      8         except (AttributeError, KeyError, TypeError):
      9             return DataFrame()

/home/pi/.local/lib/python3.7/site-packages/pykrx/website/krx/market/wrap.py in get_index_ohlcv_by_date(fromdate, todate, ticker)
    383         20190131  2222.879883  2222.879883  2201.219971  2204.850098  545248000
    384     """
--> 385     df = MKD20011_SUB().fetch(fromdate, todate, ticker[1:], ticker[0])
    386     df = df[['trd_dd', 'opnprc_idx', 'hgprc_idx', 'lwprc_idx',
    387              'clsprc_idx', 'acc_trdvol']]

/home/pi/.local/lib/python3.7/site-packages/pykrx/website/krx/market/core.py in fetch(self, fromdate, todate, index, market)
    299         idx_cd = "1{}".format(index)
    300         result = self.post(idx_cd=idx_cd, ind_tp_cd=market, idx_ind_cd=index, bz_dd=todate,
--> 301                            chartType="line", chartStandard="srate", fromdate=fromdate, todate=todate)
    302         return DataFrame(result['output'])
    303 

/home/pi/.local/lib/python3.7/site-packages/pykrx/website/krx/krxio.py in post(self, **params)
     15         params.update({"code": otp.text})
     16         resp = super().read(**params)
---> 17         return resp.json()
     18 
     19     @property

/usr/lib/python3/dist-packages/requests/models.py in json(self, **kwargs)
    895                     # used.
    896                     pass
--> 897         return complexjson.loads(self.text, **kwargs)
    898 
    899     @property

/usr/lib/python3/dist-packages/simplejson/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    516             parse_constant is None and object_pairs_hook is None
    517             and not use_decimal and not kw):
--> 518         return _default_decoder.decode(s)
    519     if cls is None:
    520         cls = JSONDecoder

/usr/lib/python3/dist-packages/simplejson/decoder.py in decode(self, s, _w, _PY3)
    368         if _PY3 and isinstance(s, bytes):
    369             s = str(s, self.encoding)
--> 370         obj, end = self.raw_decode(s)
    371         end = _w(s, end).end()
    372         if end != len(s):

/usr/lib/python3/dist-packages/simplejson/decoder.py in raw_decode(self, s, idx, _w, _PY3)
    398             elif ord0 == 0xef and s[idx:idx + 3] == '\xef\xbb\xbf':
    399                 idx += 3
--> 400         return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

이런오류가발생해요

**Comment by hwanys2** [comment]
혹시해서 다른 컴에서 진행해봐도 역시 같은 문제이네요. 
서버에서 출력해주는 형식이 바꼈을까요 어딘가?

**Comment by mr-yoo** [comment]
안녕하세요. 
가상환경을 사용해서 깨끗한 상태에서 테스트해볼 것을 추천드립니다. 
- 가상환경 셋업 방법 : https://wikidocs.net/74394

전달해주신 코드를 실행해본 결과 정상 출력됩니다. 
```python
from pykrx import stock

today = stock.get_nearest_business_day_in_a_week()
df_stock = stock.get_market_ohlcv_by_ticker(today)
df_stock["종목명"] = df_stock["종목명"].str.upper()
df_stock = df_stock.reset_index()
print(df_stock.head())
```
```text
     종목코드    종목명     시가     고가  ...         거래대금           시가총액      시총비중      상장주식수
0  000020   동화약품  20300  20500  ...  24381198450   558629400000  0.020004   27931470
1  000040  KR모터스   1125   1150  ...   1913869700    99452204530  0.000000   91661018
2  000050     경방  12050  12050  ...    355007050   330354003500  0.010002   27415270
3  000060  메리츠화재  16300  16500  ...  10185390400  1984281250000  0.090027  120625000
4  000070  삼양홀딩스  74500  74900  ...   1221170400   641463897900  0.029999    8564271
[5 rows x 11 columns]
```
테스트를 위해 `https://repl.it/`의 `Python 3.8.2`에서 확인했습니다.

**Comment by hwanys2** [comment]
이게 안될때가있나요?
자료를 가져오는 서버가 잠시 멈춘다던지 점검한다던지??

저번에도 안되다가 됐던게

오늘 또 안되네요.

한달에 한 번씩 점검하는건지...?

**Comment by mr-yoo** [comment]
최근에는 KRX 웹사이트가 새단장함에 따라 API를 모두 수정해야 했습니다.
기본적인 동작은 하는 걸 확인했으니 모듈 업데이트 후 다시 사용해 주세요.

모든 기능을 지원하진 않고 차차 업데이트 하고 있습니다. 
이런 일이 자주 있지는 않습니다..

**Comment by seojeeno** [comment]
오늘도 같은 이슈가 있는 것 같습니다 ㅠㅠ 확인부탁드립니다
