### ISSUE TITLE
일별 가격 데이터 받아 오는것이 안되는 듯 합니다.

### ISSUE THREAD

**Issue by asjgi** [sharebook-kr/pykrx#39]
최근 네이버가 페이지를 수정 이후 
해당 데이터를 가져오는게 안되는 걸로 알고 있습니다.
따라서, pd.read_html()로 구현하셨으면 Not found table로 리턴 되더라구요..
혹시 KRX에서 가져오는 자료는 없나요?

**Comment by mr-yoo** [comment]
KRX 웹페이지도 개편된 것으로 보이는데요. 확인해 보겠습니다. 

`adjusted=False` 옵션을 추가하면 KRX에서 데이터를 스크래핑합니다. 
단 KRX는 수정종가를 지원하지 않습니다. 

참고로 현재 KRX 서버가 변경된 것으로 보입니다.

**Comment by mr-yoo** [comment]
네이버 데이터를 가져오는 코드는 아래와 같습니다. 
- https://github.com/sharebook-kr/pykrx/blob/master/pykrx/website/naver/core.py
판다스를 사용하지 않아서 현재 별다른 문제는 없어 보입니다. 

#329cd68의 반영으로 KRX에서도 OHLCV 데이터까지 가져오는 것을 확인했습니다. 
`pip install -U pykrx` 업데이트후 확인 한번 부탁드립니다.

**Comment by mr-yoo** [comment]
모듈 업데이트를 완료했고 API 정상 이용 가능합니다.

**Comment by asjgi** [comment]
감사합니다!! 다시 한번 확인해 볼께요
