### ISSUE TITLE
해당 키가 바뀌었네요. 

### ISSUE THREAD

**Issue by asjgi** [sharebook-kr/pykrx#40]
https://github.com/sharebook-kr/pykrx/blob/ef9c96ad73859aa4a0d88098565d0cf06e163420/pykrx/website/krx/market/core.py#L49
코드에서는 끝이 t320으로 되어 있는데

실제 조회 싸이트 가보니 아래와 같이 바뀌어져 있는데 이것이 원인 이지 아닐까 조심스래 말씀 드려봅니다.
http://marketdata.krx.co.kr/contents/MKD/04/0402/04020100/MKD04020100T3T2.jsp

**Comment by mr-yoo** [comment]
네. 웹 사이트가 개편된 것으로 보입니다...

**Comment by mr-yoo** [comment]
#39와 같은 내용입니다.

**Comment by mr-yoo** [comment]
모듈 업데이트를 완료했습니다.
업데이트 후 에러 없이 사용 가능합니다.
