### ISSUE TITLE
get_market_trading_value_and_volume_by_ticker 를 실행하면 오류가 나옵니다.

### ISSUE THREAD

**Issue by peacmake** [sharebook-kr/pykrx#47]
오류메시지는 다음과 같습니다.
module 'pykrx.website.krx' has no attribute 'get_market_trading_value_and_volume_by_ticker'

함수가 없어진 것인지요?

**Comment by mr-yoo** [comment]
최근 KRX 웹사이트가 개편됨에 따라서 순차적으로 API를 업데이트 하고 있습니다. 업데이트된 웹 페이지에서 데이터를 제공해 준다면 추가하겠습니다. 하나씩 추가하고 있습니다.

**Comment by mr-yoo** [comment]
@peacmake 님
https://github.com/sharebook-kr/pykrx/commit/97b43b9d9e7227a036039d03dd2f7387c0a1dae4 에서 관련 기능을 추가했습니다.
최대한 유사하게 기능을 추가 했는데 수정이 필요하네요.
- [get_market_trading_volume_by_date](https://github.com/sharebook-kr/pykrx#2118-%EC%9D%BC%EC%9E%90%EB%B3%84-%EA%B1%B0%EB%9E%98%EC%8B%A4%EC%A0%81-%EC%B6%94%EC%9D%B4-%EA%B1%B0%EB%9E%98%EB%9F%89)
- [get_market_trading_value_by_date](https://github.com/sharebook-kr/pykrx#2117-%EC%9D%BC%EC%9E%90%EB%B3%84-%EA%B1%B0%EB%9E%98%EC%8B%A4%EC%A0%81-%EC%B6%94%EC%9D%B4-%EA%B1%B0%EB%9E%98%EB%8C%80%EA%B8%88)
- [get_market_trading_value_by_investor](https://github.com/sharebook-kr/pykrx#2119-%ED%88%AC%EC%9E%90%EC%9E%90%EB%B3%84-%EA%B1%B0%EB%9E%98%EC%8B%A4%EC%A0%81-%EC%B6%94%EC%9D%B4-%EA%B1%B0%EB%9E%98%EB%8C%80%EA%B8%88)
- [get_market_trading_volume_by_investor](https://github.com/sharebook-kr/pykrx#21110-%ED%88%AC%EC%9E%90%EC%9E%90%EB%B3%84-%EA%B1%B0%EB%9E%98%EC%8B%A4%EC%A0%81-%EC%B6%94%EC%9D%B4-%EA%B1%B0%EB%9E%98%EB%9F%89)
- [get_market_net_purchases_of_equities_by_ticker](https://github.com/sharebook-kr/pykrx#21111-%ED%88%AC%EC%9E%90%EC%9E%90%EB%B3%84-%EC%88%9C%EB%A7%A4%EC%88%98-%EC%83%81%EC%9C%84%EC%A2%85%EB%AA%A9)


기존에 사용하던 것과 유사한 함수 `get_market_net_purchases_of_equities_by_ticker` 입니다. 
참고해주세요. 

소스 코드는 반영했으며, pykrx에 대한 업데이트는 웹 서버 변경 사항 더 수정하고 v.1.1.0에서 올릴 예정입니다.

**Comment by mr-yoo** [comment]
@peacmake 변경 사항을 pypi에 업데이트 했습니다. 

모듈 업데이트 후 확인 부탁드립니다. 
reporting 늘 감사드립니다.
