### ISSUE TITLE
get_market_trading_volume_by_date 함수 다시 한번 확인 부탁 드립니다

### ISSUE THREAD

**Issue by jssunkorea** [sharebook-kr/pykrx#54]
여전히 18개만 출력 됩니다
stock.get_exhaustion_rates_of_foreign_investment_by_ticker("20210118","KOSPI")

**Comment by mr-yoo** [comment]
@jssunkorea 

온라인 (깨끗한 환경)에서 실행한 결과 정상적으로 결과가 나옵니다. 
https://repl.it/@Jonghunyoo/pykrxissues54

![image](https://user-images.githubusercontent.com/29349211/106457101-d3d7a680-64d1-11eb-99e7-7262b2847239.png)

버전을 확인해 주실 수 있을까요?

```python
import pykrx
print(pykrx.__version__)
```
```text
'1.0.7'
```

**Comment by jssunkorea** [comment]
pykrx 버전이 1.0.6 이었는데, 
버전 1.0.7 로 올리니 정상적으로 출력 됩니다.
감사합니다!
