### ISSUE TITLE
get_market_fundamental_by_date함수 maket= 설정 확인바랍니다.

### ISSUE THREAD

**Issue by Thebinggoo** [sharebook-kr/pykrx#55]
\pykrx\website\krx\market\wrap.py

def get_market_fundamental_by_date(fromdate: str, todate: str, ticker:str, market: str="KOSPI") -> DataFrame:
로 되어 있습니다.

def get_market_fundamental_by_date(fromdate: str, todate: str, ticker:str, market: str="ALL") -> DataFrame:
로 수정하니 코스닥도 잘 나옵니다.

**Comment by mr-yoo** [comment]
일부 API가 ALL 파라미터를 지정할 수 없는 것들이 있어서 일관된 동작을 위해 모든 API가 KOSPI 시장을 조회하도록 수정했습니다. 아직 문서는 업데이트 중입니다.

**Comment by mr-yoo** [comment]
눈에 띄도록 문서도 `코스피`로 강조해 놨습니다.
https://github.com/sharebook-kr/pykrx#2111-ticker-%EC%A1%B0%ED%9A%8C
