### ISSUE TITLE
why e3 module deleted?

### ISSUE THREAD

**Issue by tyolee** [sharebook-kr/pykrx#6]
I have used e3 module to get ETF OHLCV.

but from version 0.1.8, e3 module deleted.

why?

is there any plan for update e3 module?

**Comment by mr-yoo** [comment]
I will modify the KRX module this year. By then, I will finish checking APIs related to ETF market.

**Comment by mr-yoo** [comment]
I’m sorry this is so late. OHLCV, PDF, tracking error, and price deviation API were added to the pykrx module. 
I wrote a brief API description on the following link.
- https://github.com/sharebook-kr/pykrx#22-e3-api
