### ISSUE TITLE
KOSDAQ Ticker 들이 stock.get_market_fundamental_by_date 조회가 되지 않는 이슈

### ISSUE THREAD

**Issue by gangilseo** [sharebook-kr/pykrx#60]
현재 KRX 전 종목에 대해 데이터를 수집하여 테스트중인데,
코스닥 종목중 다수가 stock.get_market_fundamental_by_date(fromdate, todate, ticker)로 했을때
[] 결과를 반환하는 이슈를 확인했습니다.

여러번 확인한결과 서버에 잦은 요청으로인해 누락된것 같지는 않은데, 이에 대해 코멘트 주시면 감사하겠습니다.

**Comment by mr-yoo** [comment]
최근 웹서버가 변경됨에 따라 많은 수정이 있었습니다. 
모듈 업그레이드 부탁드립니다. 

`pip install -U pykrx`

```python
import pykrx
print(pykrx.__version__)
```
```
1.0.9
```

최신 버전임에도 에러가 발생한다면 빈 DataFrame
을 반환했던 사용 코드를 첨부해 주실 수 있을까요?

**Comment by traeper** [comment]
안녕하세요. 
저도 같은 현상이 있네요.

```
>>> import pykrx
>>> print(pykrx.__version__)
1.0.9
>>> stock.get_market_fundamental_by_date("20200101", "20200430", "263720", freq="m")
Empty DataFrame
Columns: []
Index: []
```

**Comment by mr-yoo** [comment]
@traeper @gangilseo 님
지적해주신것과 같이 코스닥 시장의 결과가 올바르지 않은 것을 확인했습니다.

**Comment by mr-yoo** [comment]
코스닥 시장의 종목 조회가 안되던 문제를 해결했습니다. (https://github.com/sharebook-kr/pykrx/commit/a7e00cb11689e1d8073cff0f40bc2afe26807910)

```python
from pykrx import stock
df = stock.get_market_fundamental_by_date("20200101", "20200430", "263720")
print(df)
```

```text
             BPS    PER   PBR  EPS  DIV  DPS
날짜
2020-01-02  3033  48.78  6.59  410  0.0    0
2020-01-03  3033  45.24  6.12  410  0.0    0
2020-01-06  3033  43.90  5.93  410  0.0    0
2020-01-07  3033  45.73  6.18  410  0.0    0
2020-01-08  3033  44.15  5.97  410  0.0    0
```

코드는 merge 했으며 모듈은 하루 내에 업데이트 될 예정입니다.
