### ISSUE TITLE
티커 개수 조회

### ISSUE THREAD

**Issue by ud803** [sharebook-kr/pykrx#61]
안녕하세요, 티커 개수를 조회하는 함수를 호출했을 때의 리스트 개수와, 한국거래소 http://clearingl.krx.co.kr/main/main.jsp에 나오는 KOSPI 상장사의 개수가 일치하지 않는 것 같은데, 어느 쪽이 잘못된 걸까요?

금일 기준 함수 실행값은 921개, 한국거래소는 803개가 나오네요!

`tickers = get_market_ticker_list()`
`print(len(set(tickers)))`

**Comment by mr-yoo** [comment]
상장사의 개수는 803개가 맞을겁니다.
다만 티커에는 우선주 등이 포함되어 921개입니다.

전종목 시세 페이지를 참고하면 2021-02-10 기준으로 921개의 티커가 출력됩니다. 
http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020101
