### ISSUE TITLE
JSONDecodeError 간혹 뜨는데 저만그런가요?

### ISSUE THREAD

**Issue by hwanys2** [sharebook-kr/pykrx#62]
잘 되다가 한 번씩
JSONDecodeError

오류가 뜨는데 이게 크롤링이 특정시간에 안되서 그런건가요?

지금은

pdf = stock.get_index_portfolio_deposit_file("1028")

요거 하면 에러가 뜨네요 ㅠ

**Comment by mr-yoo** [comment]
간헐적으로 증상이 재현된다면 network가 불안정하지 않을까 싶습니다..

**Comment by jaem-seo** [comment]
현재도 마찬가지입니다. 다른 function은 괜찮은데 stock.get_index_portfolio_deposit_file() 만 간헐적으로 그러네요..

**Comment by jasonleejusuk** [comment]
저도 가끔 뜨는데.. 패턴이 없습니다. 네트웍도 멀쩡한데... 쩝.
