### ISSUE TITLE
get_market_price_change_by_ticker 함수 ValueError: invalid literal for int() with base 10: '-' 발생합니다.

### ISSUE THREAD

**Issue by stat17-hb** [sharebook-kr/pykrx#63]
```python
from pykrx import stock
df = stock.get_market_price_change_by_ticker(fromdate="20210101", todate="20210111")
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-fb5f17d51594> in <module>
----> 1 df = stock.get_market_price_change_by_ticker(fromdate="20210101", todate="20210111")
      2 df.head()

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pykrx\stock\api.py in get_market_price_change_by_ticker(fromdate, todate)
    367         todate = _datetime2string(todate)
    368 
--> 369     df_a = krx.get_market_price_change_by_ticker(fromdate, todate)
    370     if df_a.empty:
    371         return df_a

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pykrx\website\comm\util.py in wrapper(*args, **kwargs)
      5     def wrapper(*args, **kwargs):
      6         try:
----> 7             return func(*args, **kwargs)
      8         except (AttributeError, KeyError, TypeError) as e:
      9             logging.info(e)

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pykrx\website\krx\market\wrap.py in get_market_price_change_by_ticker(fromdate, todate, market, adjusted)
    283     df = df.astype({"시가": np.int32, "종가": np.int32,
    284                     "변동폭": np.int32, "등락률": np.float64,
--> 285                     "거래량": np.int64, "거래대금": np.int64})
    286     return df
    287 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors)
   5531                 if col_name in dtype:
   5532                     results.append(
-> 5533                         col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
   5534                     )
   5535                 else:

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\generic.py in astype(self, dtype, copy, errors)
   5546         else:
   5547             # else, only a single dtype is given
-> 5548             new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
   5549             return self._constructor(new_data).__finalize__(self, method="astype")
   5550 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\internals\managers.py in astype(self, dtype, copy, errors)
    602         self, dtype, copy: bool = False, errors: str = "raise"
    603     ) -> "BlockManager":
--> 604         return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
    605 
    606     def convert(

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\internals\managers.py in apply(self, f, align_keys, **kwargs)
    407                 applied = b.apply(f, **kwargs)
    408             else:
--> 409                 applied = getattr(b, f)(**kwargs)
    410             result_blocks = _extend_blocks(applied, result_blocks)
    411 

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\internals\blocks.py in astype(self, dtype, copy, errors)
    593             vals1d = values.ravel()
    594             try:
--> 595                 values = astype_nansafe(vals1d, dtype, copy=True)
    596             except (ValueError, TypeError):
    597                 # e.g. astype_nansafe can fail on object-dtype of strings

~\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\dtypes\cast.py in astype_nansafe(arr, dtype, copy, skipna)
    972         # work around NumPy brokenness, #1987
    973         if np.issubdtype(dtype.type, np.integer):
--> 974             return lib.astype_intsafe(arr.ravel(), dtype).reshape(arr.shape)
    975 
    976         # if we have a datetime/timedelta array of objects

pandas\_libs\lib.pyx in pandas._libs.lib.astype_intsafe()

ValueError: invalid literal for int() with base 10: '-'

데이터 타입을 int로 강제해서 생기는 문제인 것 같습니다. 확인 부탁드립니다.

**Comment by GunhaHwang** [comment]
저도 같은 문제가 발생해서 확인해보니까
website.krx.market.wrap.py의
get_market_price_change_by_ticker 함수에서 데이터 타입을 변경하는 부분에서 문제가 발생하는 것 같습니다.
` df = df.astype({"시가": np.int32, "종가": np.int32,
                    "변동폭": np.int32, "등락률": np.float64,
                    "거래량": np.int64, "거래대금": np.int64})`

위 부분의 바로 앞에 아래와 같이 처리를 해주니 문제가 없어졌습니다.
`    def ifelse(boo, a, b):
        if boo:
            return a
        else:
            return b
    df['시가'] = df['시가'].apply(lambda row : ifelse(row =='-', '0', row ))
    df['종가'] = df['종가'].apply(lambda row: ifelse(row == '-', '0', row))
    df['변동폭'] = df['변동폭'].apply(lambda row: ifelse(row == '-', '0', row))
    df['등락률'] = df['등락률'].apply(lambda row: ifelse(row == '-', '0', row))
    df['거래량'] = df['거래량'].apply(lambda row: ifelse(row == '-', '0', row))
    df['거래대금'] = df['거래대금'].apply(lambda row: ifelse(row == '-', '0', row))`

**Comment by mr-yoo** [comment]
결측값 제거 로직의 버그를 수정했습니다.

![image](https://user-images.githubusercontent.com/29349211/109896286-01339200-7cd4-11eb-9a87-d660cd95068d.png)

코드는 반영했고 모듈은 몇일 내로 업데이트 될 예정입니다.

**Comment by mr-yoo** [comment]
#### 최신 버전으로 모듈 업데이트 확인
```python
import pykrx 
print(pykrx.__version__)
```
`1.0.11`

#### 결과 확인
```python
from pykrx import stock
df = stock.get_market_price_change_by_ticker(fromdate="20210101", todate="20210111")
print(df.head()
```
```text
            종목명      시가      종가  변동폭    등락률       거래량          거래대금
티커
095570   AJ네트웍스    4615    4360 -255 -553.0   3445854   16332546190
006840    AK홀딩스   25150   24800 -350 -139.0    605351   15190840550
027410      BGF    4895    4690 -205 -419.0   3296226   16198124270
282330   BGF리테일  135500  135500    0    0.0    399330   54474898000
138930  BNK금융지주    5680    5720   40   70.0  22211455  125465685660
```

정상 동작을 확인했습니다. 
감사합니다.
