### ISSUE TITLE
get_market_fundamental_by_date 오래된 데이터를 못가져옴

### ISSUE THREAD

**Issue by rivston2** [sharebook-kr/pykrx#69]
stock.get_market_fundamental_by_date(fromdate="20141201", todate="20210130", ticker="068270")
krx 사이트에는 데이터가 있던데 2018-02-09 부터 밖에 못가져오네요.
네이버에서 가져오게 되있는건가요?

stock.get_market_fundamental_by_date(fromdate="20141201", todate="20210130", ticker="035420")
근데 이건 또 잘 가져오네요.

**Comment by mr-yoo** [comment]
과거 셀트리온이 코스닥 시장에서 코스피 시장으로 이전상장했습니다. 
현재 API는 코스피 시장 데이터만 조회 했습니다. 
모든 데이터를 조회하도록 d168b03ea6c1c951e80f3b3987e29bfab522570c 에서 수정했습니다. 

모듈은 몇일 이내에 업데이트 될 예정입니다.

**Comment by mr-yoo** [comment]
모듈 업데이트 완료했습니다!
