### ISSUE TITLE
2.1.1.11 value error

### ISSUE THREAD

**Issue by woonkij** [sharebook-kr/pykrx#77]
투자자별 순 매수 상위종목 쿼리에 에러가 있습니다.

`df = stock.get_market_trading_volume_by_investor("20210115", "20210122", "005930")`
`print(df.head())`

Value Error: invalid literal for int() with base 10: 
라는 에러가 나오고, 구문을 살펴보니 종목명을 int()로 캐스팅 하면서 생기는 에러 같습니다. 확인해주실 수 있으실까요? 감사합니다.

**Comment by mr-yoo** [comment]
재현이 안되는데 모듈 업데이트 하고 확인해 주실 수 있나요?
`pip install -U pykrx`


```python
import pykrx
print(pykrx.__version__)
```
`1.0.14`

**Comment by woonkij** [comment]
회사 linux 언어 환경 문제로 다운로드가 되지 않았습니다. 새로운 패키지를 설치 한 뒤 해결되었습니다. 감사합니다.
