### ISSUE TITLE
ETF PDF 오류의견

### ISSUE THREAD

**Issue by bayesiankim** [sharebook-kr/pykrx#79]
좋은 라이브러리 사용할 수 있게되어 무척 고맙습니다.

한가지 오류가 발견되어서 말씀드리고자 합니다.

ETF PDF 데이터를 보면 간혹 PDF에 포함된 종목중에 선물(101R90) 계약수 정보가 제공되고 있쟎습니까?

그런데 선물은 롱이지 숏인지 구별이 되어야 하는데 일률적으로 롱으로 표기가 되어 있더라구요.

참고로 KODEX인버스의 경우 숏포지션이라서 "-3.28"로 표시되어야하는데 "3.28"로 되어 있습니다.

이 부분 수정되어야 할 것으로 보입니다.

좋은 성과 있으시길 기대하겠습니다.

고맙습니다

**Comment by spar7453** [comment]
krx.etx.wrap에서


거래소 사이트에서 내용이 없는 부분은 '-'를 줘서 타입 캐스팅이 안되기 떄문에 '-'를 0으로 바꿔주는 줄이 있는데

140번째줄에
# - empty string은 int, float로 형변환 불가
# -  -> 이 문제를 해결하기 위해 '-' 문자는 0으로 치환
df = df.replace('-', '0', regex=True)

여기서 문제가 생깁니다
스트링 사이즈 비교해서 1일 경우만 바꿔주면 해결될 것 같네요

**Comment by mr-yoo** [comment]
@spar7453 분석 감사합니다. 

`-` 기호를 0으로 변경하던 다음 코드를 수정했습니다. 
`df = df.replace('-', '0', regex=True)`

`-`가 단독으로 사용될 때만 변경합니다. 
`df = df.replace('\-$', '0', regex=True)`

다음과 같이 코드의 동작을 확인 했구요.
```
df = stock.get_etf_portfolio_deposit_file("114800", "20210705")
print(df)
```
```
           계약수                    금액   비중
티커
069500 -325.00                     0  0.0
101R90   -3.28  18446744073352277616  0.0
```
