### ISSUE TITLE
주가가 이상합니다. 

### ISSUE THREAD

**Issue by pinotlabcode** [sharebook-kr/pykrx#87]
주가 정보가 이상하게 나와서 문의 합니다. 
2015년에 삼성전자 주가를 가져와 보면 2만원대로 나옵니다.
이상한데요 확인좀 부탁드립니다.
(참고로 pykrx버젼은 1.0.19입니다)

from pykrx import stock
df = stock.get_market_ohlcv_by_date("20150130", "20150130", "005930")
print(df)
               시가     고가     저가     종가     거래량
날짜                                            
2015-01-30  27200  27540  27200  27300  322200

**Comment by mr-yoo** [comment]
수정 종가라서 그렇습니다. 현재 모듈에서는 수정종가를 네이버에서 가져옵니다. 

만약 보정하지 않은 값을 얻어오고 싶다면 `adjusted` 파라미터를 추가해 주시면 됩니다. 
```python
df = stock.get_market_ohlcv_by_date("20150130", "20150130", "005930", adjusted=False)
print(df)
```
```
                 시가       고가       저가       종가     거래량          거래대금   등락률
날짜                     
2015-01-30  1360000  1377000  1360000  1365000  322200  440683045910  0.37                                                   
```
