### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jswoo** [sharebook-kr/pykrx#9]
tickers = stock.get_market_ticker_list() 시 발생. 

몇주전에는 정상 동작 했었는데.. 

다른 함수도 몇가지 동일한 오류.. ㅠㅠ

**Comment by WOOJOONSIK** [comment]
다시 작동 되네요..^^

**Comment by mr-yoo** [comment]
최신 버전으로 업데이트 한 번 부탁드려요.
감사합니다!

`pip install -U pykrx`
