### ISSUE TITLE
펀더멘탈 조회시 연간 말고 분기로도 조회

### ISSUE THREAD

**Issue by unhokang** [sharebook-kr/pykrx#94]
펀더멘탈 조회시 일단위 월단위로 조회가 가능한데 bps eps 값이 연간 기준으로 조회가 됩니다. 혹시 이를 분기 bps 분기 eps로 조회가 가능한지 궁금합니다.

**Comment by mr-yoo** [comment]
다음 웹페이지의 정보를 그대로 가져오고 있습니다. 
http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0202

정보가 저장된 웹싸이트를 알려주시면 업데이트할 수는 있습니다.
