### ISSUE TITLE
함수 오류가 있는 것 같습니다

### ISSUE THREAD

**Issue by realyou0312** [sharebook-kr/pykrx#95]
![image](https://user-images.githubusercontent.com/76391662/143798024-4d0fc777-c9d0-4076-b175-e951586d3b6c.png)

pykrx 에 해당 함수가 없다고 나옵니다.. ㅠㅠ  제가 문제인건가요..?

**Comment by mr-yoo** [comment]
어제 코드를 업데이트 했습니다. 최신 기능으로 반영하는데 하루 정도 걸릴 예정이에요.  

아래와 함수는 특정 일자의 전종목 시가/고가/저가/종가를 조회합니다.

```python
df = stock.get_market_ohlcv_by_ticker("20211126")
```

특정 기간동안의 한 종목의 정보를 조회하고 싶다면 다음 함수를 사용하세요. 날짭려로 정렬된 데이터를 반환합니다.

```python
df = Stock.get_market_ohlcv_by_date("20210101", "20210115", "005930")
```
------

최신 업데이트는  위 두 함수를 합쳐서 get_market_ohlcv 하나로 사용하게 할 예정입니다. 내일 부터는 사용하실 수 있을 거에요.

**Comment by mr-yoo** [comment]
모듈 업데이트 완료됐습니다. 모듈 재설치 해주세요.
`pip install -U pykrx`

업데이트가 잘 됐는지 버전을 확인해주세요.
```python
import pykrx
print(pykrx.__version__)
```
`1.0.28`

----

이제는 메뉴얼과 일치하게 코드가 동작합니다. 

```python
from pykrx import stock

df = stock.get_market_ohlcv("20211126")
df.head()
```

하필 모듈 업데이트하는 시점에 사용하셔서 불편함을 유발했네요.
즐거운 코딩되세요.
