### ISSUE TITLE
AttributeError: module 'pykrx.stock' has no attribute 'get_index_fundamental' 에러

### ISSUE THREAD

**Issue by JeongSangjin** [sharebook-kr/pykrx#96]
안녕하세요!
좋은 모듈 만들어주셔서 감사의 인사를 먼저 드립니다.

아래 그림과 같이 펀더멘탈 함수만 오류가 나오네요..

![image](https://user-images.githubusercontent.com/72198330/144036456-207afa44-4cad-442a-8c72-a3da4335c4cf.png)

**Comment by mr-yoo** [comment]
모듈 업데이트하고 다시 실행해 보세요.
`pip install -U pykrx`

**Comment by JeongSangjin** [comment]
아!! 빠르게 해결해주셔서 감사합니다 :))
좋은 하루 되세요!!
