### ISSUE TITLE
"기업 주요 변동사항" 데이터 수집 문의

### ISSUE THREAD

**Issue by namdori61** [sharebook-kr/pykrx#98]
안녕하세요~ pykrx 감사히 잘 사용하고 있습니다!

이용하다보니 pykrx에서 지원하지 않는 데이터 중, KRX 정보 데이터 시스템에서 수집하고 싶은 데이터가 생겼는데요.
혹시 이 모듈의 `KrxWebIo` 를 이용해서, "기업 주요 변동사항 (http://data.krx.co.kr/contents/MDC/HARD/hardController/MDCHARD048.cmd)" 역시 티커 별로 수집이 가능할까요?

작성해주신 모듈을 참고해서 신규 모듈을 만들어보려했으나, 몇가지 이해가 안되는 부분이 있어서 아래와 같이 질문 드립니다.

pykrx/website/krx/market/core.py의 `전종목시세` 클래스를 예시로 들면,
`"dbms/MDC/STAT/standard/MDCSTAT01501"` 로 데이터의 위치를 지정해주는 것으로 이해가 되는데요.

실제로 웹사이트 화면 기준으로 살펴보면, 위의 데이터 위치를 유추할만한 정보가 없습니다.
url 도 `http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201` 이고, 화면번호 역시 12001 입니다.

제가 수집하고자하는 "기업 주요 변동사항"의 url 은 `http://data.krx.co.kr/contents/MDC/HARD/hardController/MDCHARD048.cmd` 인데요. 만약에 `KrxWebIo` 를 이용해서, 수집이 가능하다면 데이터 위치 정보는 어떻게 얻을 수 있을까요?

감사합니다!

**Comment by mr-yoo** [comment]
웹브라우저의 개발자도구 혹은 네트워크 패킷을 분석하는 툴을 사용해서 웹사이트를 분석해야 합니다. `파이썬 스크래핑`을 키워드로 검색해 보시면 관련된 정보가 나올겁니다.

**Comment by mr-yoo** [comment]
스크래핑하는 코드를 업데이트했습니다.
- https://github.com/sharebook-kr/pykrx/commit/0c600495a66a5b3737e57bec3b52a9665bddad88

pip에는 아직 반영되지 않았습니다.

**Comment by namdori61** [comment]
@mr-yoo 
우와 정말 빠른 답변 및 처리 감사드립니다!

**Comment by mr-yoo** [comment]
모듈 업데이트 후에 사용하실 수 있습니다.
`pip install -U pykrx`

```python
from pykrx import stock

df = stock.get_stock_major_changes("005930")
df
```

버그가 있을 수 있습니다. 문제가 있다면 알려주세요^^
